import {useRef,useState} from 'react';
import {ScrollView,View,Text,Pressable,ActivityIndicator,KeyboardAvoidingView,Platform} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as SecureStore from 'expo-secure-store';
import {StatusBar} from 'expo-status-bar';
import type {Order,Role} from '../web/src/types';
import {useWorkspace} from './hooks/useWorkspace';
import {Button,s} from './ui';
import {OrderTicket} from './features/OrderTicket';
import {WaiterScreen} from './features/WaiterScreen';
import {KitchenScreen} from './features/KitchenScreen';
import {CashierScreen} from './features/CashierScreen';
import {AdminScreen} from './features/AdminScreen';
import {StaffTools} from './features/StaffTools';
import {PrinterTools} from './features/PrinterTools';

const roleNames:Record<Role,string>={Waiter:'Orders',Kitchen:'Kitchen',Cashier:'Payments',Admin:'Manage'};
export default function App(config:{API:string;sessionKey:string;onChangeServer:()=>void}){
 const workspace=useWorkspace(config);const {pushStatus,acceptSession,localKey,token,setToken,user,setUser,data,setData,role,setRole,setTab,email,setEmail,password,setPassword,busy,error,live,lastSync,syncError,syncing,pending,setDraftReady,setCart,setInstructions,writes,api,refresh,run,signIn,field,API,sessionKey,onChangeServer}=workspace;
 const [tools,setTools]=useState(false);const scroll=useRef<ScrollView>(null);
 async function signOut(){await writes.current;if(user)await AsyncStorage.removeItem(localKey(user.id,'state'));await SecureStore.deleteItemAsync(sessionKey);setToken('');setUser(null);setData(null);setDraftReady('');setCart({});setInstructions('');setTools(false);}
 if(!user)return <SafeAreaView style={s.safe}><StatusBar style="dark"/><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={{flex:1}}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.login}><Text style={s.brand}>tableflow.</Text><View style={[s.card,{backgroundColor:'#193e32',borderColor:'#193e32',padding:25,marginVertical:20}]}><Text style={{color:'#d6e6b5',fontSize:11,letterSpacing:1.5,fontWeight:'600'}}>A SMOOTHER SHIFT</Text><Text style={[s.h1,{color:'#f4f8ec',fontSize:30,marginTop:18}]}>Good food.{ '\n'}Great service.</Text><Text style={[s.body,{color:'#aac39b',fontSize:13,marginTop:8}]}>A little more room for hospitality.</Text></View><Text style={s.eyebrow}>WELCOME BACK</Text><Text style={s.h1}>Let’s make it a good one.</Text><Text style={s.body}>Sign in to your restaurant workspace.</Text>{field('Email address',email,setEmail)}{field('Password',password,setPassword,true)}{!!error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}<Button title={busy?'Signing you in…':'Open my workspace'} disabled={busy||!email||!password} onPress={signIn}/><Button title="Connect to another restaurant" secondary disabled={busy} onPress={onChangeServer}/></ScrollView></KeyboardAvoidingView></SafeAreaView>;
 if(!data)return <SafeAreaView style={s.safe}><View style={[s.content,{flex:1,justifyContent:'center',alignItems:'center'}]}><Text style={s.brand}>tableflow.</Text><ActivityIndicator color="#205a45" size="large"/><Text style={s.body}>{error||syncError||'Getting your workspace ready…'}</Text><Button title="Try again" disabled={syncing} onPress={()=>void refresh()}/><Button title="Back to sign in" secondary onPress={()=>void signOut()}/></View></SafeAreaView>;
 const card=(o:Order)=><View key={o.id}><OrderTicket o={o} role={role} busy={busy} run={run}/><PrinterTools API={API} token={token} kind="kot" id={o.id}/></View>;
 const active=data.orders.filter(o=>!['Paid','Voided'].includes(o.status)&&(role!=='Waiter'||o.waiterId===user.id));const ready=active.filter(o=>o.status==='Ready');
 function select(r:Role){setRole(r);setTab('Order');setTools(false);scroll.current?.scrollTo({y:0,animated:false});}
 return <SafeAreaView style={s.safe}><StatusBar style="dark"/><View style={s.header}><Text style={[s.brand,{color:'#f3f7ec',fontSize:26}]}>tableflow.</Text><View style={{flexDirection:'row',gap:7,alignItems:'center'}}><View style={s.dot}/><Text style={{fontSize:10,color:'#bccea8'}}>{live}</Text></View></View><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView ref={scroll} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View><Text style={s.eyebrow}>{tools?'YOUR WORKSPACE':`HELLO, ${user.name.split(' ')[0].toUpperCase()}`}</Text><Text style={s.h1}>{tools?'Staff & settings':role==='Waiter'?'Good service starts here.':role==='Kitchen'?'Ready for the rush.':role==='Cashier'?'A great meal, all settled.':'Your restaurant, in order.'}</Text><Text style={[s.body,{fontSize:13}]}>{tools?'Everything you need for a smooth handover.':role==='Waiter'?'Choose a table. Find a favourite. Send it to the kitchen.':role==='Kitchen'?'See what’s cooking and what needs you next.':role==='Cashier'?'Review the bill and record payments with confidence.':'Manage your menu, team, and daily service.'}</Text></View>
 {!!error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}
 {!tools&&<View style={s.metrics}>{[['Tables',data.sessions.length],['Active orders',active.filter(o=>o.status!=='Served').length],['Ready to serve',ready.length]].map(([name,value])=><View key={String(name)} style={[s.metric,name==='Ready to serve'&&{backgroundColor:'#eef4e1'}]}><Text style={s.metricLabel}>{name}</Text><Text style={s.metricValue}>{value}</Text></View>)}</View>}
 <View style={s.row}><Text style={[s.meta,{flex:1,fontSize:10}]}>{syncError?'Connection needs attention':syncing?'Updating…':lastSync?'Updated '+new Date(lastSync).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'Showing saved workspace'}</Text><Pressable accessibilityRole="button" accessibilityLabel="Refresh workspace" disabled={syncing} onPress={()=>void refresh()} style={{padding:10,minHeight:42,justifyContent:'center'}}><Text style={[s.link,{fontSize:11}]}>Refresh ↻</Text></Pressable></View>{!!syncError&&<Text style={s.note}>{syncError}</Text>}
 {!!pending&&<View style={s.card}><Text style={s.h2}>Let’s check your last order</Text><Text style={s.body}>Table {pending.body.tableId} · Your order is saved. Confirm it before sending another.</Text><Button title="Check confirmation" disabled={busy} onPress={()=>void run('/orders',pending.body)}/></View>}
 {!tools&&<>{role==='Waiter'&&<WaiterScreen workspace={workspace} card={card}/>} {role==='Kitchen'&&<KitchenScreen workspace={workspace} card={card}/>} {role==='Cashier'&&<CashierScreen workspace={workspace} card={card}/>} {role==='Admin'&&<AdminScreen workspace={workspace}/>}</>}
 {tools&&<><View style={s.card}><Text style={s.h2}>{user.name}</Text><Text style={s.meta}>{user.role} · Branch {user.branchId||1}</Text><Text style={s.meta}>{pushStatus||'Foreground order alerts are active.'}</Text></View><StaffTools user={user} data={data} api={api} onSession={acceptSession} refresh={refresh}/><Text style={s.h2}>Notifications</Text>{data.notifications.filter(n=>n.userId===user.id&&!n.read).map(n=><View key={n.id} style={s.card}><Text style={s.item}>{n.message}</Text><Button title="Mark as read" secondary onPress={()=>void run('/notifications/'+n.id+'/read',{})}/></View>)}<Button title="Sign out of this workspace" secondary onPress={()=>void signOut()}/></>}
 </ScrollView></KeyboardAvoidingView><View style={s.bottomNav}>{(user.role==='Admin'?['Waiter','Kitchen','Cashier','Admin'] as Role[]:[user.role]).map(r=><Pressable accessibilityRole="tab" accessibilityState={{selected:!tools&&role===r}} key={r} onPress={()=>select(r)} style={[s.bottomItem,!tools&&role===r&&s.bottomItemActive]}><View style={[s.dot,{backgroundColor:!tools&&role===r?'#5b8243':'#d4dfc7'}]}/><Text style={[s.bottomText,!tools&&role===r&&s.bottomTextActive]}>{roleNames[r]}</Text></Pressable>)}<Pressable accessibilityRole="tab" accessibilityState={{selected:tools}} onPress={()=>{setTools(true);scroll.current?.scrollTo({y:0,animated:false});}} style={[s.bottomItem,tools&&s.bottomItemActive]}><View style={[s.dot,{backgroundColor:tools?'#5b8243':'#d4dfc7'}]}/><Text style={[s.bottomText,tools&&s.bottomTextActive]}>My shift</Text></Pressable></View></SafeAreaView>;
}
