import { SafeAreaView } from 'react-native-safe-area-context';
import React, { useState, useEffect, useRef, useMemo } from 'react';
import { ScrollView, View, Text, TextInput, Pressable, StyleSheet, Alert, ActivityIndicator, AppState, KeyboardAvoidingView, Platform } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { randomUUID } from 'expo-crypto';
import { jsonRequest, RequestError, sendOrder, orderSignature, coalescedRefresh } from '../shared/network.mjs';
import * as SecureStore from 'expo-secure-store';
import { StatusBar } from 'expo-status-bar';
import { HubConnectionBuilder } from '@microsoft/signalr';
import type { State, User, Order, Role } from '../web/src/types';


const draftBody = (d: any) => ({ tableId: d.table, items: Object.entries(d.cart || {}).filter(([, q]) => Number(q) > 0).map(([id, q]) => ({ menuItemId: Number(id), quantity: Number(q) })), instructions: d.notes || '' });
const money = (n: number) => `₹${n.toFixed(2)}`;
const sum = (o: Order) => o.items.reduce((n, i) => n + i.quantity * i.unitPrice, 0);
function Button({ title, onPress, disabled = false, secondary = false }: { title: string; onPress: () => void; disabled?: boolean; secondary?: boolean }) { return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[s.button, secondary && s.secondary, disabled && { opacity: .4 }]}><Text style={[s.buttonText, secondary && { color: '#165b45' }]}>{title}</Text></Pressable>; }
export default function App({ API, sessionKey, onChangeServer }: { API: string; sessionKey: string; onChangeServer: () => void }) {
    const localKey = (id: string, kind: string) => `tableflow:${API}:${id}:${kind}`;



    const [token, setToken] = useState(''); const [user, setUser] = useState<User | null>(null); const [data, setData] = useState<State | null>(null); const [role, setRole] = useState<Role>('Waiter'); const [tab, setTab] = useState('Order'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [live, setLive] = useState('Connecting'); const [table, setTable] = useState(1); const [cart, setCart] = useState<Record<number, number>>({}); const [instructions, setInstructions] = useState(''); const [query, setQuery] = useState(''); const [category, setCategory] = useState(0); const [paymentMethod, setPaymentMethod] = useState(1); const [reference, setReference] = useState(''); const [adminSection, setAdminSection] = useState('menu'); const [edit, setEdit] = useState<any>(null);
    const [lastSync, setLastSync] = useState(0); const [syncError, setSyncError] = useState(''); const [syncing, setSyncing] = useState(false); const [pending, setPending] = useState<any>(null); const [draftReady, setDraftReady] = useState(''); const [draftError, setDraftError] = useState('');
    const posting = useRef(false); const currentAuth = useRef(token); currentAuth.current = token; const draftRef = useRef({ table, cart, notes: instructions }); draftRef.current = { table, cart, notes: instructions }; const writes = useRef(Promise.resolve());
    async function api(path: string, method = 'GET', body?: unknown, auth = token) { try { return await jsonRequest(API + '/api' + path, { method, body, token: auth }); } catch (e) { if (e instanceof RequestError && e.status === 401 && path !== '/auth/login' && currentAuth.current === auth) { await SecureStore.deleteItemAsync(sessionKey); setToken(''); setUser(null); setData(null); } throw e; } }
    const refresh = useMemo(() => coalescedRefresh(async () => { const auth = token; setSyncing(true); try { const next = await api('/state'); if (currentAuth.current !== auth) return; setData(next); setSyncError(''); setLastSync(Date.now()); setLive('Connected'); if (user) void AsyncStorage.setItem(localKey(user.id, 'state'), JSON.stringify({ at: Date.now(), value: next })).catch(() => { }); } catch (e) { if (currentAuth.current === auth) { setSyncError((e as Error).message); setLive('Connection interrupted'); } } finally { if (currentAuth.current === auth) setSyncing(false); } }), [token, user?.id]);
    useEffect(() => { SecureStore.getItemAsync(sessionKey).then(v => { if (v) { try { const session = JSON.parse(v); if (Date.parse(session.expires) <= Date.now()) { void SecureStore.deleteItemAsync(sessionKey); return; } setToken(session.token); setUser(session.user); setRole(session.user.role); } catch { void SecureStore.deleteItemAsync(sessionKey); } } }); }, []);
    useEffect(() => { if (!user) return; let cancelled = false; const id = user.id; setDraftReady(''); void (async () => { try { const [draft, cached, unconfirmed] = await Promise.all(['draft', 'state', 'pending'].map(kind => AsyncStorage.getItem(localKey(id, kind)))); if (cancelled) return; const d = draft ? JSON.parse(draft) : { table: 1, cart: {}, notes: '' }; setTable(d.table); setCart(d.cart); setInstructions(d.notes); setPending(unconfirmed ? JSON.parse(unconfirmed) : null); if (cached) { const c = JSON.parse(cached); if (Date.now() - c.at < 86400000) setData(previous => previous || c.value); } setDraftReady(id); } catch { if (!cancelled) setDraftError('Unable to restore device storage. Keep this screen open.'); } })(); return () => { cancelled = true; }; }, [user?.id]);
    useEffect(() => { if (!user || draftReady !== user.id) return; const key = localKey(user.id, 'draft'); const value = JSON.stringify({ table, cart, notes: instructions }); writes.current = writes.current.catch(() => { }).then(() => AsyncStorage.setItem(key, value)).then(() => setDraftError('')).catch(() => setDraftError('Draft could not be saved on this device. Keep this screen open.')); }, [user?.id, draftReady, table, cart, instructions]);
    useEffect(() => { if (!token || !user) return; let stopped = false; let retry: ReturnType<typeof setTimeout>; let debounce: ReturnType<typeof setTimeout>; let attempt = 0; let foreground = AppState.currentState === 'active'; const sync = () => { clearTimeout(debounce); debounce = setTimeout(() => { if (!stopped && foreground) void refresh(); }, 350); }; void refresh(); const hub = new HubConnectionBuilder().withUrl(API + '/hubs/orders', { accessTokenFactory: () => token }).withAutomaticReconnect([0, 2000, 5000, 15000, 30000]).build(); hub.on('StateChanged', sync); hub.on('FoodReady', n => { Alert.alert('Food ready', n.message); sync(); }); hub.onreconnecting(() => setLive('Reconnecting')); hub.onreconnected(() => { setLive('Connected'); sync(); }); const start = () => { if (stopped || !foreground || hub.state !== 'Disconnected') return; void hub.start().then(() => { attempt = 0; setLive('Connected'); sync(); }).catch(() => { setLive('Reconnecting'); if (!stopped) retry = setTimeout(start, Math.min(30000, 2000 * 2 ** Math.min(attempt++, 4))); }); }; hub.onclose(() => { if (!stopped) retry = setTimeout(start, 5000); }); start(); const interval = setInterval(sync, 90000); const listener = AppState.addEventListener('change', state => { foreground = state === 'active'; if (foreground) { sync(); start(); } }); return () => { stopped = true; clearTimeout(retry); clearTimeout(debounce); clearInterval(interval); listener.remove(); void hub.stop(); }; }, [token, user?.id]);
    async function run(path: string, body: any, method = 'POST') { if (posting.current || !user) return false; posting.current = true; setBusy(true); setError(''); const id = user.id; try { if (path === '/orders') { await sendOrder({ body, uuid: randomUUID, read: async () => { const value = await AsyncStorage.getItem(localKey(id, 'pending')); return value ? JSON.parse(value) : null; }, write: async value => { await AsyncStorage.setItem(localKey(id, 'pending'), JSON.stringify(value)); if (currentAuth.current === token) setPending(value); }, remove: async confirmed => { if (confirmed) { await writes.current; const saved = await AsyncStorage.getItem(localKey(id, 'draft')); if (saved && orderSignature(draftBody(JSON.parse(saved))) === orderSignature(body)) await AsyncStorage.removeItem(localKey(id, 'draft')); } await AsyncStorage.removeItem(localKey(id, 'pending')); if (currentAuth.current === token) setPending(null); }, send: payload => api(path, method, payload) }); if (currentAuth.current !== token) return false; if (orderSignature(draftBody(draftRef.current)) === orderSignature(body)) { setCart({}); setInstructions(''); } } else await api(path, method, body); void refresh(); return true; } catch (e) { setError((e as Error).message); return false; } finally { posting.current = false; setBusy(false); } }
    async function signIn() { setBusy(true); try { const session = await api('/auth/login', 'POST', { email, password }); await SecureStore.setItemAsync(sessionKey, JSON.stringify(session)); setToken(session.token); setUser(session.user); setRole(session.user.role); setPassword(''); setError(''); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
    const field = (label: string, value: string, onChange: (v: string) => void, secure = false) => <View style={s.field}><Text style={s.label}>{label}</Text><TextInput style={s.input} value={value} onChangeText={onChange} secureTextEntry={secure} autoCapitalize="none" /></View>;

    if (!user) return <SafeAreaView style={s.safe}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={{ flex: 1 }}><ScrollView contentContainerStyle={s.login}><Text style={s.brand}>tableflow.</Text><Text style={s.h1}>Welcome to your shift.</Text><Text style={s.body}>Sign in to your restaurant workspace.</Text><Text style={s.meta}>{API}</Text>{field('Email', email, setEmail)}{field('Password', password, setPassword, true)}{!!error && <Text style={s.error}>{error}</Text>}<Button title={busy ? 'Signing in…' : 'Sign in'} disabled={busy || !email || !password} onPress={signIn} /><Button title="Change restaurant server" secondary disabled={busy} onPress={onChangeServer} /></ScrollView></KeyboardAvoidingView></SafeAreaView>;
    if (!data) return <SafeAreaView style={s.safe}><View style={s.content}>{syncing && <ActivityIndicator />}<Text>{error || syncError || 'Opening your workspace…'}</Text><Button title="Retry connection" disabled={syncing} onPress={() => void refresh()} /><Button title="Back to sign in" secondary onPress={() => { void SecureStore.deleteItemAsync(sessionKey); setUser(null); setToken(''); setData(null); }} /></View></SafeAreaView>;
    const add = (id: number, delta: number) => setCart(c => ({ ...c, [id]: Math.max(0, Math.min(99, (c[id] || 0) + delta)) }));
    const own = data.orders.filter(o => role !== 'Waiter' || o.waiterId === user.id);
    const card = (o: Order) => <View style={s.card} key={o.id}><View style={s.row}><Text style={s.h2}>Table {o.tableId}</Text><Text style={s.badge}>{o.status}</Text></View><Text style={s.meta}>#{o.id.slice(0, 6)} · {new Date(o.createdAt).toLocaleTimeString()}</Text>{o.items.map((i, n) => <Text style={s.item} key={n}>{i.quantity} × {i.name}</Text>)}{!!o.instructions && <Text style={s.note}>{o.instructions}</Text>}{role !== 'Kitchen' && <Text style={s.h2}>{money(sum(o))}</Text>}{role === 'Kitchen' && ['New', 'Preparing'].includes(o.status) && <Button disabled={busy} title={o.status === 'New' ? 'Start preparing' : 'Mark ready'} onPress={() => run(`/orders/${o.id}/status`, { status: o.status === 'New' ? 'Preparing' : 'Ready' })} />} {role === 'Waiter' && o.status === 'Ready' && <Button title="Mark served" disabled={busy} onPress={() => run(`/orders/${o.id}/status`, { status: 'Served' })} />}</View>;
    return <SafeAreaView style={s.safe}><StatusBar style="dark" /><View style={s.header}><Text style={s.brand}>tableflow.</Text><Text style={s.meta}>{live}</Text><Pressable accessibilityRole="button" onPress={async () => { await writes.current; await AsyncStorage.removeItem(localKey(user.id, 'state')); await SecureStore.deleteItemAsync(sessionKey); setToken(''); setUser(null); setData(null); setDraftReady(''); setCart({}); setInstructions(''); }}><Text style={s.link}>Sign out</Text></Pressable></View><KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Text style={s.meta}>{user.name} · {role}</Text><Text style={s.h1}>{role === 'Waiter' ? 'Service, made simple.' : role === 'Kitchen' ? 'On the pass.' : role === 'Cashier' ? 'Billing & payments' : 'Restaurant control'}</Text>{user.role === 'Admin' && <View style={s.wrap}>{(['Waiter', 'Kitchen', 'Cashier', 'Admin'] as Role[]).map(r => <Button title={r} key={r} secondary={r !== role} onPress={() => setRole(r)} />)}</View>}{!!error && <Text accessibilityRole="alert" style={s.error}>{error}</Text>}{data.notifications.filter(n => n.userId === user.id && !n.read).map(n => <View key={n.id} style={s.note}><Text>{n.message}</Text><Button title="Dismiss" secondary onPress={() => run(`/notifications/${n.id}/read`, {})} /></View>)}
        {<View style={s.note}><Text>{syncing ? 'Checking for updates…' : lastSync ? 'Last updated ' + new Date(lastSync).toLocaleTimeString() : 'Showing the saved workspace'}</Text>{!!syncError && <Text>{syncError}</Text>}<Button title="Refresh status" secondary disabled={syncing} onPress={() => void refresh()} /></View>}
        {!!pending && <View style={s.note}><Text style={s.h2}>Order confirmation pending · Table {pending.body.tableId}</Text><Text>Your order is saved on this device. Check confirmation before placing it again.</Text><Button title="Check order confirmation" disabled={busy} onPress={async () => { if (await run('/orders', pending.body)) Alert.alert('Order confirmed', 'The kitchen received the order.'); }} /></View>}
        {role === 'Waiter' && <><Text style={s.meta}>{draftError || draftReady !== user.id ? 'Restoring or saving draft… ' + draftError : 'Draft saved on this device · Send when connected.'}</Text><View style={s.wrap}>{['Order', 'My orders', 'Food ready'].map(t => <Button title={t} key={t} secondary={tab !== t} onPress={() => setTab(t)} />)}</View>{tab === 'Order' ? <><Text style={s.h2}>1. Select a table</Text><View style={s.wrap}>{data.tables.filter(t => t.active).map(t => <Pressable accessibilityRole="button" key={t.id} onPress={() => setTable(t.id)} style={[s.table, table === t.id && s.tableSelected]}><Text style={table === t.id ? { color: 'white' } : s.label}>{t.name}</Text><Text style={[s.meta, table === t.id && { color: '#c3ddcf' }]}>{data.sessions.some(x => x.tableId === t.id && !x.closedAt) ? 'In service' : `${t.seats} seats`}</Text></Pressable>)}</View><Text style={s.h2}>2. Build the order</Text>{field('Search menu', query, setQuery)}<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.wrap}>{[{ id: 0, name: 'All' }, ...data.categories].map(c => <Button title={c.name} key={c.id} secondary={category !== c.id} onPress={() => setCategory(c.id)} />)}</ScrollView>{data.menu.filter(m => m.active && (category === 0 || m.categoryId === category) && m.name.toLowerCase().includes(query.toLowerCase())).map(m => <View style={s.card} key={m.id}><Text style={s.h2}>{m.name}</Text><Text style={s.meta}>{m.vegetarian ? 'Vegetarian' : 'Non vegetarian'} · {m.description}</Text><View style={s.row}><Text style={s.body}>{money(m.price)}</Text><View style={s.wrap}><Button title="−" secondary onPress={() => add(m.id, -1)} /><Text style={s.body}>{cart[m.id] || 0}</Text><Button title="+" secondary onPress={() => add(m.id, 1)} /></View></View></View>)}<Text style={s.h2}>Current order · Table {table}</Text>{data.menu.filter(m => cart[m.id]).map(m => <Text key={m.id} style={s.item}>{cart[m.id]} × {m.name} — {money(cart[m.id] * m.price)}</Text>)}{field('Special instructions (optional)', instructions, v => setInstructions(v.slice(0, 500)))}<Text style={s.h2}>Total {money(data.menu.reduce((n, m) => n + (cart[m.id] || 0) * m.price, 0))}</Text><Button title="Send to kitchen" disabled={busy || draftReady !== user.id || !Object.values(cart).some(x => x > 0)} onPress={async () => { if (await run('/orders', { tableId: table, items: Object.entries(cart).filter(([, q]) => q > 0).map(([id, quantity]) => ({ menuItemId: Number(id), quantity })), instructions })) { Alert.alert('Order sent', 'The kitchen has received your order.'); } }} /></> : <>{own.filter(o => tab === 'Food ready' ? o.status === 'Ready' : o.status !== 'Paid').map(card)}{!own.some(o => tab === 'Food ready' ? o.status === 'Ready' : o.status !== 'Paid') && <Text style={s.body}>No orders here right now.</Text>}</>}</>}
        {role === 'Kitchen' && <>{['New', 'Preparing', 'Ready'].map(status => <View key={status}><Text style={s.h2}>{status} · {data.orders.filter(o => o.status === status).length}</Text>{data.orders.filter(o => o.status === status).map(card)}</View>)}</>}
        {role === 'Cashier' && <>{data.sessions.filter(session => !session.closedAt && data.orders.some(o => o.sessionId === session.id && o.status === 'Served')).map(session => { const orders = data.orders.filter(o => o.sessionId === session.id); const total = orders.reduce((n, o) => n + sum(o), 0); return <View style={s.card} key={session.id}><Text style={s.h2}>Table {session.tableId}</Text>{orders.flatMap(o => o.items).map((i, n) => <Text style={s.item} key={n}>{i.quantity} × {i.name} · {money(i.quantity * i.unitPrice)}</Text>)}<Text style={s.h2}>Total {money(total)}</Text><View style={s.wrap}>{data.paymentMethods.filter(m => m.active).map(m => <Button title={m.name} key={m.id} secondary={paymentMethod !== m.id} onPress={() => setPaymentMethod(m.id)} />)}</View>{field('Transaction reference (optional)', reference, v => setReference(v.slice(0, 120)))}<Text style={s.meta}>Confirm receipt of payment before closing this table.</Text><Button title="Confirm payment & close table" disabled={busy || orders.some(o => o.status !== 'Served')} onPress={() => Alert.alert('Confirm payment', `Have you received ${money(total)}?`, [{ text: 'Cancel', style: 'cancel' }, { text: 'Payment received', onPress: async () => { if (await run(`/sessions/${session.id}/pay`, { paymentMethodId: paymentMethod, reference, expectedTotal: Math.round(total * 100) / 100 })) { setReference(''); Alert.alert('Paid', 'The table is now available.'); } } }])} />{orders.some(o => o.status !== 'Served') && <Text style={s.note}>Serve all orders before payment.</Text>}</View>; })}<Text style={s.h2}>Recent payments</Text>{data.bills.slice(0, 20).map(b => <View key={b.id} style={s.card}><Text>Table {b.tableId} · {money(b.total)} · Paid</Text><Text style={s.meta}>{new Date(b.paidAt).toLocaleString()}</Text></View>)}</>}
        {role === 'Admin' && <><View style={s.wrap}>{[['menu', 'Menu'], ['categories', 'Categories'], ['tables', 'Tables'], ['users', 'Users & roles'], ['paymentMethods', 'Payments'], ['sales', 'Daily sales'], ['history', 'History']].map(([id, name]) => <Button title={name} key={id} secondary={adminSection !== id} onPress={() => { setAdminSection(id); setEdit(null); }} />)}</View>{adminSection === 'sales' ? <MobileSales api={api} data={data} /> : adminSection === 'history' ? <MobileHistory api={api} /> : <><Button title="Add record" onPress={() => setEdit({ id: adminSection === 'users' ? '00000000-0000-0000-0000-000000000000' : 0, name: '', description: '', price: 0, categoryId: data.categories[0]?.id, active: true, vegetarian: true, seats: 4, email: '', role: 'Waiter', password: '' })} />{edit && <View style={s.card}>{field('Name', edit.name, v => setEdit({ ...edit, name: v }))}{adminSection === 'menu' && <>{field('Description', edit.description, v => setEdit({ ...edit, description: v }))}{field('Price', String(edit.price), v => setEdit({ ...edit, price: v }))}<Text style={s.label}>Category</Text><View style={s.wrap}>{data.categories.map(c => <Button key={c.id} title={c.name} secondary={edit.categoryId !== c.id} onPress={() => setEdit({ ...edit, categoryId: c.id })} />)}</View><Button title={edit.vegetarian ? 'Vegetarian ✓' : 'Non vegetarian'} secondary onPress={() => setEdit({ ...edit, vegetarian: !edit.vegetarian })} /></>}{adminSection === 'tables' && field('Seats', String(edit.seats), v => setEdit({ ...edit, seats: v }))}{adminSection === 'users' && <>{field('Email', edit.email, v => setEdit({ ...edit, email: v }))}{field('Password (12+ characters; blank to keep)', edit.password, v => setEdit({ ...edit, password: v }), true)}<View style={s.wrap}>{data.roles.map(r => <Button title={r} key={r} secondary={edit.role !== r} onPress={() => setEdit({ ...edit, role: r })} />)}</View></>}{adminSection !== 'categories' && <Button title={edit.active ? 'Active ✓' : 'Inactive'} secondary onPress={() => setEdit({ ...edit, active: !edit.active })} />}<Button title="Save changes" disabled={busy} onPress={async () => { if (await run(`/admin/${adminSection}/${edit.id}`, { ...edit, price: Number(edit.price || 0), seats: Number(edit.seats || 4) }, 'PUT')) setEdit(null); }} /><Button title="Cancel" secondary onPress={() => setEdit(null)} /></View>}{((data as any)[adminSection] || []).map((r: any) => <View style={s.card} key={r.id}><Text style={s.h2}>{r.name}</Text><Text style={s.meta}>{adminSection === 'menu' ? money(r.price) : r.role || r.email || r.seats && `${r.seats} seats` || ''}{r.active === false ? ' · Inactive' : ''}</Text><Button title="Edit" secondary onPress={() => setEdit({ ...r, password: '' })} /></View>)}</>}</>}
    </ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
function MobileSales({ api, data }: { api: (p: string) => Promise<any>; data: State }) { const [report, setReport] = useState<any>(null); const [error, setError] = useState(''); useEffect(() => { const from = new Date(); from.setHours(0, 0, 0, 0); const to = new Date(from); to.setDate(to.getDate() + 1); api(`/admin/sales?from=${encodeURIComponent(from.toISOString())}&to=${encodeURIComponent(to.toISOString())}`).then(setReport).catch(e => setError(e.message)); }, [data]); return <View style={s.card}><Text style={s.h2}>Sales today</Text><Text style={s.h1}>{money(report?.total || 0)}</Text><Text style={s.body}>{report?.count || 0} paid bills</Text>{report?.byMethod?.map((m: any) => <Text key={m.paymentMethodId} style={s.item}>{data.paymentMethods.find(p => p.id === m.paymentMethodId)?.name}: {money(m.total)}</Text>)}{!!error && <Text style={s.error}>{error}</Text>}</View>; }
function MobileHistory({ api }: { api: (p: string) => Promise<any> }) { const [page, setPage] = useState(1); const [rows, setRows] = useState<Order[]>([]); const [error, setError] = useState(''); useEffect(() => { api(`/admin/history?page=${page}`).then(setRows).catch(e => setError(e.message)); }, [page]); return <>{rows.map(o => <View style={s.card} key={o.id}><Text style={s.h2}>Table {o.tableId} · {o.status}</Text><Text style={s.meta}>{new Date(o.createdAt).toLocaleString()}</Text>{o.items.map((i, n) => <Text style={s.item} key={n}>{i.quantity} × {i.name}</Text>)}<Text>{money(sum(o))}</Text></View>)}{!!error && <Text style={s.error}>{error}</Text>}<View style={s.wrap}><Button title="Previous" secondary disabled={page === 1} onPress={() => setPage(p => p - 1)} /><Text>Page {page}</Text><Button title="Next" secondary disabled={rows.length < 50} onPress={() => setPage(p => p + 1)} /></View></>; }
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#f6f8f5' }, header: { padding: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#fff', borderBottomWidth: 1, borderBottomColor: '#e0e8de' }, brand: { fontSize: 28, fontWeight: '800', color: '#174e39', letterSpacing: -1 }, content: { padding: 20, paddingBottom: 60, gap: 15 }, login: { padding: 28, paddingTop: 65, gap: 15 }, h1: { fontSize: 27, fontWeight: '700', color: '#263e30', marginVertical: 12 }, h2: { fontSize: 18, fontWeight: '600', color: '#314d38', marginVertical: 8 }, body: { fontSize: 16, color: '#62755d', lineHeight: 25 }, meta: { fontSize: 12, color: '#8a9a81', marginVertical: 5 }, label: { fontSize: 14, color: '#536d4a', marginBottom: 6 }, field: { marginVertical: 7 }, input: { borderWidth: 1, borderColor: '#d9e4d1', borderRadius: 8, padding: 13, fontSize: 16, color: '#314d38', backgroundColor: 'white' }, button: { backgroundColor: '#165b45', paddingHorizontal: 16, paddingVertical: 13, borderRadius: 8, alignItems: 'center', justifyContent: 'center', marginVertical: 4, minHeight: 44 }, buttonText: { color: 'white', fontSize: 14, fontWeight: '600' }, secondary: { backgroundColor: '#e8f0e3' }, wrap: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 8 }, row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 }, table: { padding: 14, borderWidth: 1, borderColor: '#dae5d1', borderRadius: 8, width: '30%', backgroundColor: 'white' }, tableSelected: { backgroundColor: '#165b45', borderColor: '#165b45' }, card: { padding: 18, backgroundColor: 'white', borderWidth: 1, borderColor: '#e0e8d9', borderRadius: 12, marginVertical: 7, gap: 5 }, badge: { padding: 7, backgroundColor: '#eaf1e3', color: '#5e7a4a', borderRadius: 6, fontSize: 12 }, item: { fontSize: 15, color: '#576f4c', paddingVertical: 6 }, note: { backgroundColor: '#f8f1dc', padding: 12, borderRadius: 7, color: '#8c763c', fontSize: 14, marginVertical: 9 }, error: { padding: 12, backgroundColor: '#fff0e9', color: '#a15543', borderRadius: 8, fontSize: 14 }, link: { color: '#63894d', fontSize: 13 } });
