import {Pressable,Text,StyleSheet} from 'react-native';
import type {Order} from '../web/src/types';
export const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(n);
export const sum=(o:Order)=>o.items.reduce((n,i)=>n+i.quantity*i.unitPrice,0);
export function Button({title,onPress,disabled=false,secondary=false,accessibilityLabel}:{title:string;onPress:()=>void;disabled?:boolean;secondary?:boolean;accessibilityLabel?:string}){
 return <Pressable accessibilityRole="button" accessibilityLabel={accessibilityLabel||title} accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={({pressed})=>[s.button,secondary&&s.secondary,disabled&&{opacity:.48},pressed&&!disabled&&{opacity:.8,transform:[{scale:.985}]}]}><Text style={[s.buttonText,secondary&&{color:'#46623c'}]}>{title}</Text></Pressable>;
}
export const s=StyleSheet.create({
 safe:{flex:1,backgroundColor:'#f6f7f2'},header:{paddingHorizontal:22,paddingVertical:17,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:'#193e32'},
 brand:{fontSize:29,fontWeight:'800',color:'#20523b',letterSpacing:-1.3},content:{padding:20,paddingBottom:40,gap:15},login:{padding:26,paddingTop:40,gap:13},h1:{fontSize:28,fontWeight:'700',color:'#294832',letterSpacing:-.8,marginVertical:7},h2:{fontSize:18,fontWeight:'700',color:'#3b5736',letterSpacing:-.3,marginVertical:8},body:{fontSize:15,color:'#6b7e60',lineHeight:24},meta:{fontSize:12,color:'#798d6b',marginVertical:5,lineHeight:18},label:{fontSize:13,fontWeight:'600',color:'#577149',marginBottom:8},field:{marginVertical:8},input:{borderWidth:1,borderColor:'#dce5d1',borderRadius:12,padding:14,fontSize:16,color:'#324f35',backgroundColor:'white',minHeight:50},
 button:{backgroundColor:'#205a45',paddingHorizontal:18,paddingVertical:14,borderRadius:12,alignItems:'center',justifyContent:'center',marginVertical:4,minHeight:49},buttonText:{color:'#fff',fontSize:14,fontWeight:'600'},secondary:{backgroundColor:'#edf2e4',borderWidth:1,borderColor:'#dce6cf'},wrap:{flexDirection:'row',flexWrap:'wrap',alignItems:'center',gap:8},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:10},table:{padding:15,borderWidth:1,borderColor:'#dde6d1',borderRadius:12,width:'30%',backgroundColor:'white',minHeight:84},tableSelected:{backgroundColor:'#205a45',borderColor:'#205a45'},card:{padding:20,backgroundColor:'white',borderWidth:1,borderColor:'#e1e7d8',borderRadius:17,marginVertical:7,gap:7,shadowColor:'#30442c',shadowOffset:{width:0,height:3},shadowOpacity:.025,shadowRadius:10,elevation:1},badge:{paddingHorizontal:10,paddingVertical:7,backgroundColor:'#edf3e2',color:'#6b8950',borderRadius:8,fontSize:11,fontWeight:'600'},item:{fontSize:14,color:'#4e6945',paddingVertical:7,lineHeight:22},note:{backgroundColor:'#f8f0dc',padding:15,borderRadius:12,color:'#98743b',fontSize:13,marginVertical:8,lineHeight:21},error:{padding:14,backgroundColor:'#fff0e7',color:'#a2553d',borderRadius:11,fontSize:13,lineHeight:21},link:{color:'#58833f',fontSize:13,fontWeight:'600'},
 eyebrow:{fontSize:10,fontWeight:'700',letterSpacing:1.8,color:'#83966e'},chip:{paddingHorizontal:13,paddingVertical:10,borderRadius:9,backgroundColor:'#eef2e6',borderWidth:1,borderColor:'#dfe7d3',minHeight:42,justifyContent:'center'},chipActive:{backgroundColor:'#205a45',borderColor:'#205a45'},chipText:{fontSize:12,fontWeight:'600',color:'#768b63'},chipTextActive:{color:'#fff'},sectionTabs:{flexDirection:'row',backgroundColor:'#eaf0df',padding:5,borderRadius:12,gap:4},sectionTab:{flex:1,alignItems:'center',justifyContent:'center',paddingVertical:12,borderRadius:9,minHeight:45},sectionTabActive:{backgroundColor:'#fff'},sectionTabText:{fontSize:12,fontWeight:'600',color:'#7f936c'},sectionTabTextActive:{color:'#315b3b'},
 bottomNav:{flexDirection:'row',paddingHorizontal:12,paddingTop:9,paddingBottom:9,borderTopWidth:1,borderTopColor:'#e2e9d8',backgroundColor:'#fff',gap:5},bottomItem:{flex:1,alignItems:'center',justifyContent:'center',paddingVertical:12,borderRadius:11,minHeight:52,gap:5},bottomItemActive:{backgroundColor:'#edf3e1'},bottomText:{fontSize:11,fontWeight:'600',color:'#8a9c78'},bottomTextActive:{color:'#416833'},dot:{width:5,height:5,borderRadius:3,backgroundColor:'#bad18f'},metrics:{flexDirection:'row',gap:10},metric:{flex:1,backgroundColor:'#fff',borderWidth:1,borderColor:'#e2e9d6',borderRadius:13,padding:14},metricValue:{fontSize:24,fontWeight:'700',color:'#365b3c',marginVertical:5},metricLabel:{fontSize:10,color:'#83966f'},
 sheetBackdrop:{flex:1,backgroundColor:'#173b3066',justifyContent:'flex-end'},sheet:{backgroundColor:'#fafcf6',borderTopLeftRadius:25,borderTopRightRadius:25,padding:24,maxHeight:'90%'},sheetHandle:{width:40,height:4,borderRadius:2,backgroundColor:'#c7d5b9',alignSelf:'center',marginBottom:20},empty:{alignItems:'center',padding:28,gap:9},emptyIcon:{fontSize:32,color:'#9cb781'},stepLabel:{fontSize:12,fontWeight:'700',color:'#557846',marginBottom:14},menuItem:{flexDirection:'row',alignItems:'center',gap:14,padding:16,backgroundColor:'#fff',borderRadius:14,borderWidth:1,borderColor:'#e2e8d8',marginVertical:5},menuThumb:{width:60,height:65,borderRadius:12,backgroundColor:'#eef1e3',alignItems:'center',justifyContent:'center'},menuName:{fontSize:15,fontWeight:'600',color:'#365239',lineHeight:22},menuDescription:{fontSize:11,color:'#829473',lineHeight:18,marginTop:4},quantityButton:{width:44,height:44,alignItems:'center',justifyContent:'center',borderRadius:11,backgroundColor:'#edf3e1',borderWidth:1,borderColor:'#dce7cc'},quantityText:{fontSize:23,color:'#507440'},
});
