import {useEffect,useState} from 'react';
import {request,userKey} from '../../api';
import type {State,User} from '../../types';
import {money} from '../../lib/format';
import {PrintButton} from '../pos/PrintButton';
import {QrCode} from '../pos/QrCode';
type Quote={subtotal:number;discount:number;serviceCharge:number;taxes:{name:string;amount:number}[];tip:number;total:number;paid:number;outstanding:number};
export function PosBilling({state,user}:{state:State;user:User}){
 const [id,setId]=useState('');const [view,setView]=useState<any>(null);const [settings,setSettings]=useState<any>({});const [amount,setAmount]=useState('');const [method,setMethod]=useState(state.paymentMethods[0]?.id||1);const [reference,setReference]=useState('');const [guests,setGuests]=useState(2);const [custom,setCustom]=useState('');const [discount,setDiscount]=useState('0');const [discountKind,setDiscountKind]=useState('Percent');const [reason,setReason]=useState('');const [tip,setTip]=useState('0');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [assign,setAssign]=useState<Record<string,number>>({});
 const sessionId=id||state.sessions.find(s=>!s.closedAt)?.id||'';
 async function load(){if(!sessionId){setView(null);return;}const value=await request('/pos/sessions/'+sessionId);setView(value);setAmount(value.quote.outstanding.toFixed(2));setTip(String(value.quote.tip));}
 useEffect(()=>{let active=true;setView(null);if(sessionId)request('/pos/sessions/'+sessionId).then(v=>{if(active){setView(v);setAmount(v.quote.outstanding.toFixed(2));}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[sessionId,state]);
 useEffect(()=>{request('/pos/settings').then(setSettings).catch(e=>setError(e.message));},[]);
 async function execute(work:()=>Promise<unknown>){if(busy)return;setBusy(true);setError('');try{await work();await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const q:Quote|undefined=view?.quote;const lines=state.orders.filter(o=>o.sessionId===sessionId&&o.status!=='Voided').flatMap(o=>o.items);
 async function pay(){const key=userKey(user.id,'payment:'+sessionId);let body=JSON.parse(sessionStorage.getItem(key)||'null');const proposed={paymentMethodId:method,amount:Number(amount),expectedTotal:q!.total,reference};if(body&&(body.amount!==proposed.amount||body.paymentMethodId!==method||body.reference!==reference))throw new Error('A previous payment needs confirmation. Restore its details or refresh before trying another tender.');if(!body){body={requestId:crypto.randomUUID(),...proposed};sessionStorage.setItem(key,JSON.stringify(body));}await request(`/pos/sessions/${sessionId}/payments`,'POST',body);sessionStorage.removeItem(key);}
 return <section className="pos-panel"><h2>Billing & split payments</h2><label className="field-label">Visit<select value={sessionId} onChange={e=>{setId(e.target.value);setAssign({});}}><option value="">Choose a visit</option>{state.sessions.map(s=><option key={s.id} value={s.id}>Table {s.tableId}</option>)}</select></label>{error&&<p className="error" role="alert">{error}</p>}{q&&<><div className="pos-columns"><div><h3>Bill</h3>{lines.map((i,n)=><div className="payment-row" key={i.id||n}><span>{i.quantity} × {i.name}</span><strong>{money(i.quantity*i.unitPrice)}</strong></div>)}{[['Subtotal',q.subtotal],['Discount',-q.discount],['Service charge',q.serviceCharge],...q.taxes.map(t=>[t.name,t.amount]),['Tip',q.tip],['Total',q.total],['Paid',q.paid],['Balance',q.outstanding]].map(([name,value])=><div className="payment-row" key={String(name)}><span>{name}</span><strong>{money(Number(value))}</strong></div>)}<PrintButton kind="bill" id={sessionId}/>{settings.upiId&&q.outstanding>0&&<QrCode value={`upi://pay?pa=${encodeURIComponent(settings.upiId)}&pn=${encodeURIComponent(settings.businessName)}&am=${q.outstanding.toFixed(2)}&cu=INR&tn=${sessionId}`} label={`Pay ${money(q.outstanding)} by UPI`}/>}<p>Confirm receipt of payment before recording a tender.</p></div><div><h3>Record a payment</h3><label className="field-label">Amount<input type="number" min="0.01" step="0.01" max={q.outstanding} value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="field-label">Method<select value={method} onChange={e=>setMethod(Number(e.target.value))}>{state.paymentMethods.filter(m=>m.active).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label className="field-label">Reference<input maxLength={120} value={reference} onChange={e=>setReference(e.target.value)}/></label><button className="primary" disabled={busy||q.outstanding<=0} onClick={()=>void execute(pay)}>Confirm tender</button><button className="secondary" disabled={busy} onClick={()=>void execute(async()=>{const key=userKey(user.id,'payment:'+sessionId);const pending=JSON.parse(sessionStorage.getItem(key)||'null');if(!pending)throw new Error('No pending payment.');await request(`/pos/sessions/${sessionId}/payments`,'POST',pending);sessionStorage.removeItem(key);})}>Check pending payment</button><h3>Payment history</h3>{view.payments.map((p:any)=><p key={p.id}>{money(p.amount)} · {state.paymentMethods.find(m=>m.id===p.paymentMethodId)?.name} · {p.reference}</p>)}</div></div>
 <details><summary>Split the bill</summary><label className="field-label">Guests<input type="number" min="1" max="100" value={guests} onChange={e=>setGuests(Number(e.target.value))}/></label><button className="secondary" disabled={busy} onClick={()=>void execute(()=>request(`/pos/sessions/${sessionId}/split`,'POST',{mode:'Equal',guests}))}>Split equally</button><label className="field-label">Custom amounts, separated by commas<input value={custom} onChange={e=>setCustom(e.target.value)}/></label><button className="secondary" disabled={busy} onClick={()=>void execute(()=>request(`/pos/sessions/${sessionId}/split`,'POST',{mode:'Custom',guests,parts:custom.split(',').map((v,i)=>({name:`Guest ${i+1}`,amount:Number(v)}))}))}>Set custom split</button><h4>Assign item lines</h4>{lines.map((line,i)=><label className="field-label" key={line.id||i}>{line.name}<select value={assign[line.id!]||1} onChange={e=>setAssign({...assign,[line.id!]:Number(e.target.value)})}>{Array.from({length:Math.min(100,Math.max(1,guests))},(_,g)=><option key={g} value={g+1}>Guest {g+1}</option>)}</select></label>)}<button className="secondary" disabled={busy} onClick={()=>void execute(()=>request(`/pos/sessions/${sessionId}/split`,'POST',{mode:'Items',guests,parts:Array.from({length:guests},(_,g)=>({name:`Guest ${g+1}`,amount:0,itemIds:lines.filter(l=>(assign[l.id!]||1)===g+1).map(l=>l.id)}))}))}>Split by items</button>{JSON.parse(view.session.splitJson||'[]').map((p:any)=><p key={p.Name}>{p.Name}: {money(p.Amount)}</p>)}</details>
 <details><summary>Tip and authorized discount</summary><label className="field-label">Tip<input type="number" min="0" step="0.01" value={tip} onChange={e=>setTip(e.target.value)}/></label><div className="pos-actions">{[0,5,10,15].map(percent=><button className="secondary" key={percent} onClick={()=>setTip((q.subtotal*percent/100).toFixed(2))}>{percent}%</button>)}<button className="secondary" disabled={busy} onClick={()=>void execute(()=>request(`/pos/sessions/${sessionId}/tip`,'POST',{amount:Number(tip)}))}>Save tip</button></div>{user.role==='Admin'&&<><label className="field-label">Discount<select value={discountKind} onChange={e=>setDiscountKind(e.target.value)}><option>Percent</option><option>Flat</option><option>None</option></select><input type="number" min="0" value={discount} onChange={e=>setDiscount(e.target.value)}/></label><label className="field-label">Reason<input value={reason} maxLength={300} onChange={e=>setReason(e.target.value)}/></label><button className="secondary" disabled={busy||!reason.trim()} onClick={()=>void execute(()=>request(`/pos/admin/sessions/${sessionId}/discount`,'POST',{kind:discountKind,value:Number(discount),reason}))}>Authorize discount</button></>}</details>
 <button className="secondary" disabled={busy||q.outstanding<=0} onClick={()=>void execute(async()=>{const order=await request(`/pos/gateway/${sessionId}/order`,'POST',{});if(!(window as any).Razorpay)await new Promise<void>((resolve,reject)=>{const script=document.createElement('script');script.src='https://checkout.razorpay.com/v1/checkout.js';script.onload=()=>resolve();script.onerror=()=>reject(new Error('Could not load checkout.'));document.head.append(script);});new (window as any).Razorpay({key:order.keyId,order_id:order.providerOrderId,amount:Math.round(order.amount*100),currency:'INR',handler:(response:any)=>void execute(()=>request(`/pos/gateway/${order.id}/confirm`,'POST',{paymentId:response.razorpay_payment_id,signature:response.razorpay_signature,paymentMethodId:method}))}).open();})}>Open payment checkout</button>
 </>}</section>;
}
