import {useEffect,useState} from 'react';
import {View,Text,TextInput,Image} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import type {State,MenuItem} from '../../web/src/types';
import {Button,s,money} from '../ui';
type Line={menuItemId:number;quantity:number;portion:string;modifiers:{group:string;option:string}[];name:string};
export function OrderComposer({data,storageScope,busy,onSubmit}:{data:State;storageScope:string;busy:boolean;onSubmit:(body:any)=>Promise<boolean>}){
 const [table,setTable]=useState(data.tables[0]?.id||1);const [lines,setLines]=useState<Line[]>([]);const [notes,setNotes]=useState('');const [ready,setReady]=useState(false);const [error,setError]=useState('');const [chosen,setChosen]=useState<MenuItem|null>(null);const [portion,setPortion]=useState('');const [mods,setMods]=useState<Record<string,string>>({});
 useEffect(()=>{let active=true;AsyncStorage.getItem(storageScope+':composer').then(text=>{if(!active)return;if(text){const d=JSON.parse(text);setTable(d.table);setLines(d.lines);setNotes(d.notes);}setReady(true);}).catch(()=>setError('Draft storage unavailable.'));return()=>{active=false;};},[storageScope]);
 useEffect(()=>{if(ready)void AsyncStorage.setItem(storageScope+':composer',JSON.stringify({table,lines,notes})).catch(()=>setError('Draft save failed. Keep this screen open.'));},[table,lines,notes,ready]);
 const groups=JSON.parse(chosen?.modifiersJson||'[]');const portions=JSON.parse(chosen?.portionsJson||'[]');
 return <View><Text style={s.h2}>Choose table</Text><View style={s.wrap}>{data.tables.filter(t=>t.active).map(t=><Button key={t.id} title={t.name} secondary={table!==t.id} onPress={()=>setTable(t.id)}/>)}</View>{data.menu.filter(m=>m.active).map(m=><View style={s.card} key={m.id}>{!!m.photoUrl&&<Image source={{uri:m.photoUrl}} style={{width:'100%',height:120}}/>}<Text style={s.h2}>{m.name} · {money(m.price)}</Text><Button title={m.available===false?'Unavailable':'Customize & add'} disabled={m.available===false||m.stock===0} secondary onPress={()=>{setChosen(m);setPortion(JSON.parse(m.portionsJson||'[]')[0]?.Name||'');setMods({});}}/></View>)}{chosen&&<View style={s.card}><Text style={s.h2}>{chosen.name}</Text>{portions.map((p:any)=><Button key={p.Name} title={`${p.Name} · ${money(p.Price)}`} secondary={portion!==p.Name} onPress={()=>setPortion(p.Name)}/>)}{groups.map((g:any)=><View key={g.Name}><Text>{g.Name}{g.Required?' (required)':''}</Text>{!g.Required&&<Button title="None" secondary onPress={()=>setMods({...mods,[g.Name]:''})}/>} {g.Options.map((o:any)=><Button key={o.Name} title={`${o.Name} +${money(o.Price)}`} secondary={mods[g.Name]!==o.Name} onPress={()=>setMods({...mods,[g.Name]:o.Name})}/>)}</View>)}<Button title="Add to order" disabled={groups.some((g:any)=>g.Required&&!mods[g.Name])} onPress={()=>{setLines([...lines,{menuItemId:chosen.id,quantity:1,portion,modifiers:Object.entries(mods).filter(([,v])=>v).map(([group,option])=>({group,option})),name:chosen.name}]);setChosen(null);}}/><Button title="Cancel" secondary onPress={()=>setChosen(null)}/></View>}<Text style={s.h2}>Current order</Text>{lines.map((l,i)=><View key={i} style={s.card}><Text>{l.quantity} × {l.name} {l.portion} {l.modifiers.map(m=>m.option).join(', ')}</Text><View style={s.wrap}><Button title="−" secondary onPress={()=>setLines(lines.flatMap((line,index)=>index===i?(line.quantity>1?[{...line,quantity:line.quantity-1}]:[]):[line]))}/><Button title="+" secondary disabled={l.quantity>=99} onPress={()=>setLines(lines.map((line,index)=>index===i?{...line,quantity:line.quantity+1}:line))}/></View></View>)}<TextInput style={s.input} placeholder="Allergies and instructions" maxLength={500} value={notes} onChangeText={setNotes}/>{!!error&&<Text style={s.error}>{error}</Text>}<Button title="Send to kitchen" disabled={busy||!ready||!lines.length} onPress={async()=>{if(await onSubmit({tableId:table,items:lines.map(({name,...line})=>line),instructions:notes})){setLines([]);setNotes('');}}}/></View>;
}
