import {useEffect,useRef,useState} from 'react';
import {View,Text,TextInput,Image,Modal,Pressable,ScrollView} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import type {State,MenuItem} from '../../web/src/types';
import {Button,s,money} from '../ui';
type Line={menuItemId:number;quantity:number;portion:string;modifiers:{group:string;option:string}[];name:string};
type Portion={Name:string;Price:number};type Group={Name:string;Required:boolean;Options:{Name:string;Price:number}[]};
function parse<T>(value:string|undefined,fallback:T):T{try{return JSON.parse(value||'null')??fallback;}catch{return fallback;}}
export function OrderComposer({data,storageScope,busy,onSubmit}:{data:State;storageScope:string;busy:boolean;onSubmit:(body:any)=>Promise<boolean>}){
 const [step,setStep]=useState(0);const [table,setTable]=useState(data.tables[0]?.id||0);const [lines,setLines]=useState<Line[]>([]);const [notes,setNotes]=useState('');const [ready,setReady]=useState(false);const [error,setError]=useState('');const [chosen,setChosen]=useState<MenuItem|null>(null);const [portion,setPortion]=useState('');const [mods,setMods]=useState<Record<string,string>>({});const [query,setQuery]=useState('');const [category,setCategory]=useState(0);const writes=useRef(Promise.resolve());
 useEffect(()=>{let active=true;setReady(false);AsyncStorage.getItem(storageScope+':composer').then(text=>{if(!active)return;if(text){const d=JSON.parse(text);setTable(d.table);setLines(d.lines);setNotes(d.notes);}else{setLines([]);setNotes('');}setReady(true);}).catch(()=>setError('Draft storage unavailable. Keep this screen open.'));return()=>{active=false;};},[storageScope]);
 useEffect(()=>{if(ready){const value=JSON.stringify({table,lines,notes});writes.current=writes.current.catch(()=>{}).then(()=>AsyncStorage.setItem(storageScope+':composer',value)).catch(()=>setError('Draft save failed. Keep this screen open.'));}},[table,lines,notes,ready,storageScope]);
 const groups=parse<Group[]>(chosen?.modifiersJson,[]);const portions=parse<Portion[]>(chosen?.portionsJson,[]);const selected=data.tables.find(t=>t.id===table&&t.active);const count=lines.reduce((n,l)=>n+l.quantity,0);
 function price(line:Line){const item=data.menu.find(m=>m.id===line.menuItemId);if(!item)return 0;const base=parse<Portion[]>(item.portionsJson,[]).find(p=>p.Name===line.portion)?.Price??item.price;return base+line.modifiers.reduce((n,m)=>n+(parse<Group[]>(item.modifiersJson,[]).find(g=>g.Name===m.group)?.Options.find(o=>o.Name===m.option)?.Price||0),0);}
 const total=lines.reduce((n,l)=>n+price(l)*l.quantity,0);
 function add(item:MenuItem){const portions=parse<Portion[]>(item.portionsJson,[]);if(portions.length||parse<Group[]>(item.modifiersJson,[]).length){setChosen(item);setPortion(portions[0]?.Name||'');setMods({});}else{const at=lines.findIndex(l=>l.menuItemId===item.id&&!l.portion&&!l.modifiers.length);setLines(at<0?[...lines,{menuItemId:item.id,quantity:1,portion:'',modifiers:[],name:item.name}]:lines.map((l,i)=>i===at?{...l,quantity:Math.min(99,l.quantity+1)}:l));}}
 const menu=data.menu.filter(m=>m.active&&(!category||m.categoryId===category)&&m.name.toLowerCase().includes(query.toLowerCase()));
 return <View style={{gap:12}}><View style={[s.row,{marginVertical:10}]}>{['Table','Menu','Review'].map((label,i)=><Pressable key={label} accessibilityRole="tab" accessibilityState={{selected:step===i}} onPress={()=>setStep(i)} style={{flex:1,flexDirection:'row',alignItems:'center',gap:8,minHeight:44}}><View style={{width:26,height:26,borderRadius:9,backgroundColor:step===i?'#205a45':'#e7eedc',alignItems:'center',justifyContent:'center'}}><Text style={{fontSize:11,fontWeight:'700',color:step===i?'white':'#83996d'}}>{i+1}</Text></View><Text style={{fontSize:12,fontWeight:'600',color:step===i?'#3d6138':'#8b9d79'}}>{label}</Text></Pressable>)}</View>
 {step===0&&<><Text style={s.h2}>A table for your guests</Text><Text style={[s.meta,{marginTop:-5}]}>Choose where this order belongs.</Text><View style={s.wrap}>{data.tables.filter(t=>t.active).map(t=>{const occupied=data.sessions.some(s=>s.tableId===t.id&&!s.closedAt);return <Pressable key={t.id} accessibilityRole="button" accessibilityState={{selected:table===t.id}} onPress={()=>setTable(t.id)} style={[s.table,table===t.id&&s.tableSelected]}><Text style={[s.label,table===t.id&&{color:'white'}]}>{t.name}</Text><Text style={[s.meta,{fontSize:10},table===t.id&&{color:'#c2d7b3'}]}>{t.seats} seats</Text><Text style={{fontSize:9,color:table===t.id?'#d7e7c4':occupied?'#ac8b49':'#8caa70'}}>{occupied?'In service':'Available'}</Text></Pressable>;})}</View><Button title={selected?`Find dishes for ${selected.name} →`:'Choose a table first'} disabled={!selected} onPress={()=>setStep(1)}/></>}
 {step===1&&<><View style={s.row}><Text style={s.h2}>What sounds good?</Text><Text style={s.badge}>{selected?.name||'Choose table'}</Text></View><TextInput accessibilityLabel="Search menu" style={s.input} placeholder="Search for a dish or drink…" placeholderTextColor="#9bad89" value={query} onChangeText={setQuery}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8,paddingVertical:7}}>{[{id:0,name:'All items'},...data.categories].map(c=><Pressable key={c.id} accessibilityRole="button" accessibilityState={{selected:category===c.id}} style={[s.chip,category===c.id&&s.chipActive]} onPress={()=>setCategory(c.id)}><Text style={[s.chipText,category===c.id&&s.chipTextActive]}>{c.name}</Text></Pressable>)}</ScrollView>{menu.map(m=>{const unavailable=m.available===false||m.stock===0;return <View style={[s.menuItem,unavailable&&{opacity:.55}]} key={m.id}>{m.photoUrl?<Image source={{uri:m.photoUrl}} style={s.menuThumb}/>:<View style={[s.menuThumb,{backgroundColor:['#eef0e3','#f4eddf','#e7eddf','#e7ece5'][m.categoryId%4]}]}><Text style={{fontSize:25,color:'#8ca075',fontWeight:'300'}}>◉</Text></View>}<View style={{flex:1}}><Text style={s.menuName}>{m.name}</Text><Text style={s.menuDescription} numberOfLines={2}>{m.description}</Text><Text style={{fontSize:13,fontWeight:'700',color:'#577747',marginTop:7}}>{money(m.price)}</Text></View><Pressable accessibilityRole="button" accessibilityLabel={`Add ${m.name}`} disabled={unavailable} onPress={()=>add(m)} style={s.quantityButton}><Text style={[s.quantityText,{fontSize:20}]}>{unavailable?'—':'+'}</Text></Pressable></View>;})}{!menu.length&&<View style={s.empty}><Text style={s.h2}>No dishes found</Text><Text style={s.body}>Try another search or category.</Text><Button title="Show all dishes" secondary onPress={()=>{setQuery('');setCategory(0);}}/></View>}<Button title={count?`Review ${count} items · ${money(total)} →`:'Your order is empty'} disabled={!count} onPress={()=>setStep(2)}/></>}
 {step===2&&<View style={s.card}><View style={s.row}><Text style={s.h2}>Your order</Text><Text style={s.badge}>{selected?.name||'No table'}</Text></View>{lines.length?lines.map((l,i)=><View key={i} style={{paddingVertical:15,borderBottomWidth:1,borderBottomColor:'#edf1e5',gap:8}}><View style={s.row}><Text style={[s.menuName,{flex:1,fontSize:14}]}>{l.name}</Text><Text style={{fontSize:13,color:'#526e44',fontWeight:'600'}}>{money(price(l)*l.quantity)}</Text></View>{(l.portion||l.modifiers.length>0)&&<Text style={s.menuDescription}>{[l.portion,...l.modifiers.map(m=>m.option)].filter(Boolean).join(' · ')}</Text>}<View style={s.wrap}><Button title="−" accessibilityLabel={`Remove one ${l.name}`} secondary onPress={()=>setLines(lines.flatMap((line,index)=>index===i?(line.quantity>1?[{...line,quantity:line.quantity-1}]:[]):[line]))}/><Text style={s.body}>{l.quantity}</Text><Button title="+" accessibilityLabel={`Add one ${l.name}`} secondary disabled={l.quantity>=99} onPress={()=>setLines(lines.map((line,index)=>index===i?{...line,quantity:line.quantity+1}:line))}/></View></View>):<View style={s.empty}><Text style={s.h2}>Something delicious?</Text><Text style={s.body}>Add a dish from the menu to get started.</Text></View>}<Button title="＋ Add more dishes" secondary onPress={()=>setStep(1)}/><Text style={[s.label,{marginTop:14}]}>A note for the kitchen</Text><TextInput accessibilityLabel="Kitchen instructions" style={[s.input,{minHeight:85,textAlignVertical:'top'}]} multiline placeholder="Allergies, spice level, anything else…" placeholderTextColor="#9aab86" maxLength={500} value={notes} onChangeText={setNotes}/><View style={[s.row,{marginTop:18}]}><Text style={s.body}>Subtotal ({count} items)</Text><Text style={[s.h2,{fontSize:24}]}>{money(total)}</Text></View><Text style={s.meta}>Final taxes and payment are handled at reception.</Text><Button title={busy?'Sending your order…':'Send to kitchen →'} disabled={busy||!ready||!lines.length||!selected} onPress={async()=>{await writes.current;if(await onSubmit({tableId:table,items:lines.map(({name,...line})=>line),instructions:notes})){setLines([]);setNotes('');setStep(0);}}}/><Text style={[s.meta,{textAlign:'center',fontSize:10}]}>Your draft is saved on this device</Text></View>}
 {!!error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}
 <Modal visible={!!chosen} transparent animationType="slide" onRequestClose={()=>setChosen(null)}><View style={s.sheetBackdrop}><View style={s.sheet} accessibilityViewIsModal><View style={s.sheetHandle}/><ScrollView keyboardShouldPersistTaps="handled"><View style={s.row}><Text style={[s.h2,{flex:1,fontSize:23}]}>{chosen?.name}</Text><Pressable accessibilityRole="button" accessibilityLabel="Close customization" onPress={()=>setChosen(null)} style={s.quantityButton}><Text style={s.quantityText}>×</Text></Pressable></View><Text style={s.meta}>Make it just right for your guest.</Text>{portions.length>0&&<Text style={[s.label,{marginTop:20}]}>Choose a size</Text>}{portions.map(p=><Button key={p.Name} title={`${portion===p.Name?'✓  ':''}${p.Name} · ${money(p.Price)}`} secondary={portion!==p.Name} onPress={()=>setPortion(p.Name)}/>)}{groups.map(g=><View key={g.Name} style={{marginTop:20}}><Text style={s.label}>{g.Name} · {g.Required?'Required':'Optional'}</Text>{!g.Required&&<Button title="No extra" secondary={!!mods[g.Name]} onPress={()=>setMods({...mods,[g.Name]:''})}/>} {g.Options.map(o=><Button key={o.Name} title={`${mods[g.Name]===o.Name?'✓  ':''}${o.Name}${o.Price?' + '+money(o.Price):''}`} secondary={mods[g.Name]!==o.Name} onPress={()=>setMods({...mods,[g.Name]:o.Name})}/>)}</View>)}<View style={{marginTop:20}}><Button title="Add to order" disabled={groups.some(g=>g.Required&&!mods[g.Name])} onPress={()=>{if(chosen)setLines([...lines,{menuItemId:chosen.id,quantity:1,portion,modifiers:Object.entries(mods).filter(([,v])=>v).map(([group,option])=>({group,option})),name:chosen.name}]);setChosen(null);}}/></View></ScrollView></View></View></Modal></View>;
}
