import {useState} from 'react';
import {View,Text,NativeModules,PermissionsAndroid,Platform} from 'react-native';
import {Button,s} from '../ui';
const encode=(bytes:Uint8Array)=>{const chars='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';let out='';for(let i=0;i<bytes.length;i+=3){const a=bytes[i],b=bytes[i+1]||0,c=bytes[i+2]||0;out+=chars[a>>2]+chars[((a&3)<<4)|(b>>4)]+(i+1<bytes.length?chars[((b&15)<<2)|(c>>6)]:'=')+(i+2<bytes.length?chars[c&63]:'=');}return out;};
export function PrinterTools({API,token,kind,id}:{API:string;token:string;kind:'kot'|'bill';id:string}){
 const [devices,setDevices]=useState<any[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [width,setWidth]=useState(48);
 async function discover(){setError('');try{if(Platform.OS!=='android'||!NativeModules.ThermalPrinter)throw new Error('Direct Bluetooth printing requires the Android build with the thermal printer plugin.');if(Number(Platform.Version)>=31){const result=await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.BLUETOOTH_CONNECT);if(result!==PermissionsAndroid.RESULTS.GRANTED)throw new Error('Bluetooth permission is required.');}setDevices(await NativeModules.ThermalPrinter.pairedDevices());}catch(e){setError((e as Error).message);}}
 async function print(address:string){setBusy(true);setError('');try{const response=await fetch(`${API}/api/pos/print/${kind}/${id}?width=${width}&format=escpos`,{headers:{Authorization:'Bearer '+token}});if(!response.ok)throw new Error('Could not load receipt.');const bytes=new Uint8Array(await response.arrayBuffer());await NativeModules.ThermalPrinter.printBluetooth(address,encode(bytes));setError('Sent. Verify physical output before reprinting.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <View><Button title={`Bluetooth ${kind==='kot'?'KOT':'bill'}`} secondary disabled={busy} onPress={()=>void discover()}/>{devices.length>0&&<><View style={s.wrap}>{[32,48].map(w=><Button title={w===32?'58 mm':'80 mm'} key={w} secondary={width!==w} onPress={()=>setWidth(w)}/>)}</View>{devices.map(d=><Button title={`Print on ${d.name}`} key={d.address} disabled={busy} secondary onPress={()=>void print(d.address)}/>)}</>}{!!error&&<Text style={s.meta}>{error}</Text>}</View>;
}
