import {useEffect,useRef,useState} from 'react';
import {Orders} from '../../components/Orders';
import {demo,request} from '../../api';
import type {Runner} from '../../lib/actions';
import type {State} from '../../types';
export function KitchenScreen({state,busy,run}:{state:State;busy:boolean;run:Runner}){
 const [station,setStation]=useState('All');const [sound,setSound]=useState(false);const [error,setError]=useState('');const audio=useRef<AudioContext|null>(null);const seen=useRef<Set<string>|null>(null);
 useEffect(()=>{const current=new Set(state.orders.filter(o=>o.status==='New').map(o=>o.id));if(seen.current&&sound&&[...current].some(id=>!seen.current!.has(id))&&audio.current){const ctx=audio.current;const osc=ctx.createOscillator();const gain=ctx.createGain();osc.connect(gain);gain.connect(ctx.destination);osc.frequency.setValueAtTime(660,ctx.currentTime);osc.frequency.setValueAtTime(880,ctx.currentTime+.15);gain.gain.setValueAtTime(.12,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.5);osc.start();osc.stop(ctx.currentTime+.5);}seen.current=current;},[state.orders,sound]);
 useEffect(()=>()=>{void audio.current?.close();},[]);
 const orders=state.orders.filter(o=>station==='All'||o.items.some(i=>(i.station||'Kitchen')===station));
 return <><div className="pos-actions"><label>Kitchen station <select value={station} onChange={e=>setStation(e.target.value)}>{['All',...new Set(state.menu.map(m=>m.station||'Kitchen'))].map(s=><option key={s}>{s}</option>)}</select></label><button className="secondary" onClick={()=>{audio.current??=new AudioContext();void audio.current.resume();setSound(!sound);}}>{sound?'Mute new-ticket chime':'Enable new-ticket chime'}</button></div><p>Under 10 min: normal · 10–15 min: warning · Over 15 min: delayed. Status buttons update the entire order across all stations.</p><div className="kitchen-board">{['New','Preparing','Ready'].map(status=><section className="kitchen-column" key={status}><div className="column-title"><span className={`status-dot ${status}`}/><h2>{status}</h2><span>{orders.filter(o=>o.status===status).length}</span></div><Orders orders={orders.filter(o=>o.status===status)} state={state} role="Kitchen" busy={busy} run={run}/></section>)}</div>{!demo&&<details className="pos-panel"><summary>Stock & availability</summary>{error&&<p role="alert">{error}</p>}{state.menu.map(m=><div className="payment-row" key={m.id}><span>{m.name} · {m.stock??'untracked'} remaining</span><button className="secondary" disabled={busy} onClick={async()=>{try{await request(`/pos/menu/${m.id}/availability`,'POST',{available:m.available===false,stock:m.stock});}catch(e){setError((e as Error).message);}}}>{m.available===false?'Make available':'Mark unavailable'}</button><label>Stock<input aria-label={`${m.name} stock`} type="number" min="0" defaultValue={m.stock??''} onBlur={async e=>{try{await request(`/pos/menu/${m.id}/availability`,'POST',{available:e.target.value===''||Number(e.target.value)>0,stock:e.target.value===''?null:Number(e.target.value)});}catch(err){setError((err as Error).message);}}}/></label></div>)}</details>}</>;
}
