import {useEffect,useState} from 'react';
import {acceptSession,request} from '../../api';
import type {User} from '../../types';
export function AccountTools({user}:{user:User}){
 const [branches,setBranches]=useState<any[]>([]);const [staff,setStaff]=useState<any[]>([]);const [selected,setSelected]=useState('');const [pin,setPin]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{Promise.all([request('/auth/branches'),request('/auth/staff')]).then(([b,s])=>{setBranches(b);setStaff(s);}).catch(e=>setError(e.message));},[]);
 async function run(work:()=>Promise<unknown>){setBusy(true);setError('');try{await work();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <details className="pos-panel"><summary>Staff and branch</summary><p>Current branch: {branches.find(b=>b.id===user.branchId)?.name||user.branchId}</p><div className="pos-actions">{branches.filter(b=>b.id!==user.branchId).map(b=><button className="secondary" disabled={busy} key={b.id} onClick={()=>void run(async()=>acceptSession(await request('/auth/branch/'+b.id,'POST',{})))}>{b.name}</button>)}</div><label className="field-label">Four-digit PIN<input type="password" inputMode="numeric" maxLength={4} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))}/></label><button className="secondary" disabled={busy||pin.length!==4} onClick={()=>void run(async()=>{await request('/auth/pin','POST',{pin});setPin('');setError('PIN saved.');})}>Set my PIN</button><label className="field-label">Switch staff<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose staff</option>{staff.map(s=><option key={s.id} value={s.id}>{s.name} · {s.role}</option>)}</select></label><button className="primary" disabled={busy||!selected||pin.length!==4} onClick={()=>void run(async()=>acceptSession(await request('/auth/pin-login','POST',{userId:selected,pin,branchId:user.branchId||1})))}>Unlock staff workspace</button>{error&&<p role="status">{error}</p>}</details>;
}
