import {useState} from 'react';
import type {State,User} from '../../types';
import {request} from '../../api';
import {QrCode} from './QrCode';
export function FloorMap({state,user,refresh}:{state:State;user:User;refresh:()=>Promise<void>}){
 const [section,setSection]=useState('All');const [selected,setSelected]=useState(0);const [target,setTarget]=useState(0);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const table=state.tables.find(t=>t.id===selected);const session=state.sessions.find(s=>s.tableId===selected&&!s.closedAt);
 async function transfer(merge:boolean){setBusy(true);setError('');try{await request(`/pos/sessions/${session!.id}/transfer`,'POST',{tableId:target,merge});await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="pos-panel"><h2>Floor plan</h2><select aria-label="Section" value={section} onChange={e=>setSection(e.target.value)}>{['All',...new Set(state.tables.map(t=>t.section||'Main Hall'))].map(s=><option key={s}>{s}</option>)}</select><p>Green: vacant · Amber: occupied · Blue: food ready · Purple: bill requested</p><div className="floor-scroll"><div className="floor-map">{state.tables.filter(t=>t.active&&(section==='All'||(t.section||'Main Hall')===section)).map((t,index)=>{const occupied=state.sessions.some(s=>s.tableId===t.id&&!s.closedAt);const ready=state.orders.some(o=>o.tableId===t.id&&o.status==='Ready');const bill=(state as any).guestRequests?.some((r:any)=>r.tableId===t.id&&r.kind==='Bill'&&!r.resolved);return <button key={t.id} className={`floor-table ${bill?'bill-request':ready?'food-ready':occupied?'occupied':'vacant'}`} style={{left:t.x||index%4*220,top:t.y||Math.floor(index/4)*120}} onClick={()=>setSelected(t.id)}><strong>{t.name}</strong><small>{t.seats} seats · {t.section||'Main Hall'}</small></button>;})}</div></div>{error&&<p className="error">{error}</p>}{table&&<div><h3>{table.name}</h3>{table.guestToken&&<QrCode value={`${window.location.origin}/t/${table.guestToken}`} label={`Guest ordering · ${table.name}`}/>}<button className="secondary" onClick={()=>window.print()}>Print table QR</button>{session&&['Cashier','Admin'].includes(user.role)&&<><label className="field-label">Move or merge into<select value={target} onChange={e=>setTarget(Number(e.target.value))}><option value={0}>Choose table</option>{state.tables.filter(t=>t.id!==selected&&t.active).map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><div className="pos-actions"><button className="secondary" disabled={busy||!target} onClick={()=>void transfer(false)}>Transfer visit</button><button className="secondary" disabled={busy||!target} onClick={()=>void transfer(true)}>Merge visits</button></div></>}</div>}</section>;
}
