import {useEffect,useState} from 'react';
import {apiUrl} from '../../api';
import {jsonRequest,sendOrder} from '../../../../shared/network.mjs';
import {MenuPicker,type Line} from './MenuPicker';
import {money} from '../../lib/format';
import {QrCode} from './QrCode';
export function GuestPortal({token}:{token:string}){
 const key='tableflow:guest:'+token;const [data,setData]=useState<any>(null);const [lines,setLines]=useState<Line[]>(()=>{try{return JSON.parse(localStorage.getItem(key+':draft')||'[]');}catch{return [];}});const [notes,setNotes]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [visit,setVisit]=useState(()=>sessionStorage.getItem(key+':visit')||'');const [rating,setRating]=useState(5);const [comment,setComment]=useState('');
 const call=(path:string,method='GET',body?:unknown)=>jsonRequest(`${apiUrl}/api/guest/${token}${path}`,{method,body});
 useEffect(()=>{call('').then(setData).catch(e=>setError(e.message));},[token]);
 useEffect(()=>{try{localStorage.setItem(key+':draft',JSON.stringify(lines));}catch{setError('Unable to save draft on this device.');}},[lines,key]);
 async function run(work:()=>Promise<unknown>){setBusy(true);setError('');try{await work();setData(await call(''));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <main className="guest-page"><h1>{data?.businessName||'Tableflow'}</h1><h2>{data?.table.name||'Opening your table…'}</h2>{error&&<p role="status" className="error">{error}</p>}{data&&<><MenuPicker menu={data.menu} lines={lines} setLines={setLines}/><label className="field-label">Allergies or instructions<textarea maxLength={500} value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="primary" disabled={busy||!lines.length} onClick={()=>void run(async()=>{const body={tableId:data.table.id,items:lines,instructions:notes};const order=await sendOrder({body,uuid:()=>crypto.randomUUID(),read:async()=>JSON.parse(localStorage.getItem(key+':pending')||'null'),write:async p=>localStorage.setItem(key+':pending',JSON.stringify(p)),remove:async()=>localStorage.removeItem(key+':pending'),send:p=>call('/orders','POST',p)});setVisit(order.sessionId);sessionStorage.setItem(key+':visit',order.sessionId);setLines([]);setNotes('');setError('Your order is with the kitchen.');})}>Place order</button><button className="secondary" disabled={busy} onClick={()=>void run(async()=>{const p=JSON.parse(localStorage.getItem(key+':pending')||'null');if(!p)throw new Error('No pending order.');const order=await call('/orders','POST',p.body);localStorage.removeItem(key+':pending');setVisit(order.sessionId);sessionStorage.setItem(key+':visit',order.sessionId);setLines([]);})}>Check pending order</button><div className="pos-actions"><button className="secondary" disabled={busy} onClick={()=>void run(()=>call('/request','POST',{kind:'Waiter'}))}>Call waiter</button><button className="secondary" disabled={busy} onClick={()=>void run(()=>call('/request','POST',{kind:'Bill'}))}>Request bill</button><button className="secondary" disabled={busy} onClick={()=>void run(async()=>{})}>Refresh bill</button></div>{data.quote&&<div className="pos-panel"><h3>Current bill {money(data.quote.total)}</h3><p>Outstanding: {money(data.quote.outstanding)}</p>{data.upiId&&data.quote.outstanding>0&&<QrCode value={`upi://pay?pa=${encodeURIComponent(data.upiId)}&pn=${encodeURIComponent(data.businessName)}&am=${data.quote.outstanding.toFixed(2)}&cu=INR`} label="Pay outstanding balance"/>}<p>Show your payment confirmation to the cashier.</p></div>}{visit&&<details><summary>Rate your visit after payment</summary><label className="field-label">Rating<select value={rating} onChange={e=>setRating(Number(e.target.value))}>{[5,4,3,2,1].map(r=><option key={r}>{r}</option>)}</select></label><label className="field-label">Comments<textarea maxLength={1000} value={comment} onChange={e=>setComment(e.target.value)}/></label><button className="secondary" disabled={busy} onClick={()=>void run(()=>call('/feedback','POST',{sessionId:visit,rating,comment}))}>Send feedback</button></details>}</>}</main>;
}
