import {useState} from 'react';
import {Search,Plus,Minus,Trash2,ShoppingBag,Leaf,UtensilsCrossed,Check} from 'lucide-react';
import type {MenuItem} from '../../types';
import {money} from '../../lib/format';
import {Dialog} from '../../components/Dialog';

export type Line={menuItemId:number;quantity:number;portion?:string;modifiers:{group:string;option:string}[]};
export const parse=<T,>(text:string|undefined,fallback:T):T=>{try{return JSON.parse(text||'null')??fallback;}catch{return fallback;}};
export type Portion={Name:string;Price:number};
export type Group={Name:string;Required:boolean;Options:{Name:string;Price:number}[]};
export function linePrice(menu:MenuItem[],line:Line){const item=menu.find(m=>m.id===line.menuItemId);if(!item)return 0;const portion=parse<Portion[]>(item.portionsJson,[]).find(p=>p.Name===line.portion);const groups=parse<Group[]>(item.modifiersJson,[]);return (portion?.Price??item.price)+line.modifiers.reduce((sum,m)=>sum+(groups.find(g=>g.Name===m.group)?.Options.find(o=>o.Name===m.option)?.Price||0),0);}

export function OrderCart({menu,lines,setLines}:{menu:MenuItem[];lines:Line[];setLines:(lines:Line[])=>void}){
 function quantity(index:number,delta:number){setLines(lines.flatMap((line,i)=>i!==index?[line]:line.quantity+delta<=0?[]:[{...line,quantity:Math.min(99,line.quantity+delta)}]));}
 return <div className="modern-cart">{lines.length?lines.map((line,index)=>{const item=menu.find(m=>m.id===line.menuItemId);return <div className="modern-cart-line" key={index}><div className="cart-line-heading"><strong>{item?.name||'Unavailable item'}</strong><span>{money(linePrice(menu,line)*line.quantity)}</span></div>{(line.portion||line.modifiers.length>0)&&<small>{[line.portion,...line.modifiers.map(m=>m.option)].filter(Boolean).join(' · ')}</small>}<div className="cart-line-actions"><div className="quantity"><button type="button" aria-label={`Remove one ${item?.name}`} onClick={()=>quantity(index,-1)}><Minus size={15}/></button><span aria-live="polite">{line.quantity}</span><button type="button" disabled={line.quantity>=99} aria-label={`Add one ${item?.name}`} onClick={()=>quantity(index,1)}><Plus size={15}/></button></div><button className="icon-button" aria-label={`Remove ${item?.name} from order`} onClick={()=>setLines(lines.filter((_,i)=>i!==index))}><Trash2 size={15}/></button></div></div>;}):<div className="cart-empty"><div className="empty-bag"><ShoppingBag size={30}/></div><h3>Something delicious?</h3><p>Add a dish from the menu.<br/>We’ll keep the order right here.</p></div>}</div>;
}

export function MenuPicker({menu,lines,setLines,categories=[],showCart=true}:{menu:MenuItem[];lines:Line[];setLines:(lines:Line[])=>void;categories?:{id:number;name:string}[];showCart?:boolean}){
 const [query,setQuery]=useState('');const [category,setCategory]=useState(0);const [veg,setVeg]=useState(false);const [chosen,setChosen]=useState<MenuItem|null>(null);const [portion,setPortion]=useState('');const [mods,setMods]=useState<Record<string,string>>({});
 const portions=parse<Portion[]>(chosen?.portionsJson,[]);const groups=parse<Group[]>(chosen?.modifiersJson,[]);
 const visible=menu.filter(m=>m.active&&(!category||m.categoryId===category)&&(!veg||m.vegetarian)&&m.name.toLowerCase().includes(query.toLowerCase()));
 function add(item:MenuItem){if(parse<Portion[]>(item.portionsJson,[]).length||parse<Group[]>(item.modifiersJson,[]).length){setChosen(item);setPortion(parse<Portion[]>(item.portionsJson,[])[0]?.Name||'');setMods({});}else{const index=lines.findIndex(l=>l.menuItemId===item.id&&!l.portion&&!l.modifiers.length);setLines(index<0?[...lines,{menuItemId:item.id,quantity:1,modifiers:[]}]:lines.map((l,i)=>i===index?{...l,quantity:Math.min(99,l.quantity+1)}:l));}}
 return <><div className="menu-toolbar"><label className="search"><Search size={19}/><input aria-label="Search menu" placeholder="Search for a dish or drink…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button className="text-button" type="button" onClick={()=>setQuery('')}>Clear</button>}</label><button className={'diet-filter '+(veg?'selected':'')} aria-pressed={veg} onClick={()=>setVeg(!veg)}><Leaf size={17}/>Veg only</button></div>
 {categories.length>0&&<div className="category-tabs" aria-label="Menu categories">{[{id:0,name:'All items'},...categories].map(c=><button key={c.id} aria-pressed={category===c.id} className={category===c.id?'active':''} onClick={()=>setCategory(c.id)}>{c.name}</button>)}</div>}
 <div className="menu-results-heading"><h2>{categories.find(c=>c.id===category)?.name||'On the menu'}</h2><span>{visible.length} {visible.length===1?'item':'items'}</span></div>
 <div className="menu-grid modern-menu">{visible.map(m=>{const unavailable=m.available===false||m.stock===0;const count=lines.filter(l=>l.menuItemId===m.id).reduce((n,l)=>n+l.quantity,0);return <article className={'menu-card '+(unavailable?'item-unavailable':'')} key={m.id}><div className={'dish-art dish-color-'+(m.categoryId%4)}>{m.photoUrl?<img src={m.photoUrl} alt={m.name} loading="lazy"/>:<><div className="dish-plate"><UtensilsCrossed size={26}/></div><span>{categories.find(c=>c.id===m.categoryId)?.name||m.station||'Made fresh'}</span></>}{count>0&&<span className="dish-count"><Check size={12}/>{count} in order</span>}</div><div className="dish-content"><div className="dish-title"><span className={'diet '+(m.vegetarian?'veg':'nonveg')} title={m.vegetarian?'Vegetarian':'Non vegetarian'}><i/></span><h3>{m.name}</h3></div><p>{m.description||'Freshly prepared, just for your table.'}</p><div className="menu-card-bottom"><strong>{money(m.price)}{parse<Portion[]>(m.portionsJson,[]).length>0&&<small>base price</small>}</strong><button className="add-button" disabled={unavailable||count>=99} onClick={()=>add(m)}>{unavailable?'Sold out':count>=99?'Limit reached':'Add'}{!unavailable&&count<99&&<Plus size={16}/>}</button></div></div></article>;})}</div>
 {!visible.length&&<div className="empty"><Search size={28}/><h3>No dishes found</h3><p>Try another search or choose a different category.</p><button className="secondary" onClick={()=>{setQuery('');setCategory(0);setVeg(false);}}>Show all dishes</button></div>}
 {showCart&&<section className="guest-cart"><h2>Your order</h2><OrderCart menu={menu} lines={lines} setLines={setLines}/></section>}
 {chosen&&<Dialog title={chosen.name} description="Make it just right for your guest." onClose={()=>setChosen(null)}><form onSubmit={e=>{e.preventDefault();setLines([...lines,{menuItemId:chosen.id,quantity:1,portion,modifiers:Object.entries(mods).filter(([,v])=>v).map(([group,option])=>({group,option}))}]);setChosen(null);}}>{portions.length>0&&<fieldset className="choice-group"><legend>Choose a size <span>Required</span></legend>{portions.map(p=><label className={'choice-row '+(portion===p.Name?'selected':'')} key={p.Name}><input type="radio" required name="portion" checked={portion===p.Name} onChange={()=>setPortion(p.Name)}/><span>{p.Name}</span><strong>{money(p.Price)}</strong></label>)}</fieldset>}{groups.map(g=><fieldset className="choice-group" key={g.Name}><legend>{g.Name}<span>{g.Required?'Required':'Optional'}</span></legend>{!g.Required&&<label className="choice-row"><input type="radio" name={g.Name} checked={!mods[g.Name]} onChange={()=>setMods({...mods,[g.Name]:''})}/>No extra</label>}{g.Options.map(o=><label className={'choice-row '+(mods[g.Name]===o.Name?'selected':'')} key={o.Name}><input type="radio" required={g.Required} name={g.Name} checked={mods[g.Name]===o.Name} onChange={()=>setMods({...mods,[g.Name]:o.Name})}/><span>{o.Name}</span><strong>{o.Price?'+ '+money(o.Price):'Included'}</strong></label>)}</fieldset>)}<div className="dialog-actions"><button type="button" className="secondary" onClick={()=>setChosen(null)}>Cancel</button><button className="primary">Add to order<Plus size={17}/></button></div></form></Dialog>}
 </>;
}
