import {useState} from 'react';
import type {MenuItem} from '../../types';
import {money} from '../../lib/format';
export type Line={menuItemId:number;quantity:number;portion?:string;modifiers:{group:string;option:string}[]};
export const parse=<T,>(text:string|undefined,fallback:T):T=>{try{return JSON.parse(text||'null')??fallback;}catch{return fallback;}};
type Portion={Name:string;Price:number};
type Group={Name:string;Required:boolean;Options:{Name:string;Price:number}[]};
export function MenuPicker({menu,lines,setLines}:{menu:MenuItem[];lines:Line[];setLines:(lines:Line[])=>void}){
 const [query,setQuery]=useState('');const [chosen,setChosen]=useState<MenuItem|null>(null);const [portion,setPortion]=useState('');const [mods,setMods]=useState<Record<string,string>>({});
 const portions=parse<Portion[]>(chosen?.portionsJson,[]);const groups=parse<Group[]>(chosen?.modifiersJson,[]);
 return <><label className="field-label">Search menu<input value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="menu-grid">{menu.filter(m=>m.active&&m.name.toLowerCase().includes(query.toLowerCase())).map(m=><article className="menu-card" key={m.id}>{m.photoUrl&&<img className="food-photo" src={m.photoUrl} alt={m.name}/>}<h3>{m.name}</h3><p>{m.description}</p><strong>{money(m.price)}</strong><button className="secondary" disabled={m.available===false||m.stock===0} onClick={()=>{setChosen(m);setPortion(parse<Portion[]>(m.portionsJson,[])[0]?.Name||'');setMods({});}}>{m.available===false||m.stock===0?'Unavailable':'Add item'}</button></article>)}</div>
 <h3>Selected items</h3>{lines.map((line,index)=><div className="payment-row" key={index}><span>{menu.find(m=>m.id===line.menuItemId)?.name} {line.portion} {line.modifiers.map(m=>m.option).join(', ')}</span><input aria-label="Quantity" type="number" min="1" max="99" value={line.quantity} onChange={e=>setLines(lines.map((l,i)=>i===index?{...l,quantity:Math.max(1,Math.min(99,Number(e.target.value)))}:l))}/><button className="secondary" onClick={()=>setLines(lines.filter((_,i)=>i!==index))}>Remove</button></div>)}
 {chosen&&<div className="modal-backdrop"><form className="modal" role="dialog" aria-modal="true" aria-label="Customize item" onSubmit={e=>{e.preventDefault();setLines([...lines,{menuItemId:chosen.id,quantity:1,portion,modifiers:Object.entries(mods).filter(([,v])=>v).map(([group,option])=>({group,option}))}]);setChosen(null);}}><h2>{chosen.name}</h2>{portions.length>0&&<label className="field-label">Portion<select required value={portion} onChange={e=>setPortion(e.target.value)}>{portions.map(p=><option key={p.Name} value={p.Name}>{p.Name} · {money(p.Price)}</option>)}</select></label>}{groups.map(g=><label className="field-label" key={g.Name}>{g.Name} {g.Required?'(required)':'(optional)'}<select required={g.Required} value={mods[g.Name]||''} onChange={e=>setMods({...mods,[g.Name]:e.target.value})}><option value="">Choose</option>{g.Options.map(o=><option key={o.Name}>{o.Name}</option>)}</select></label>)}<div className="pos-actions"><button className="primary">Add to order</button><button type="button" className="secondary" onClick={()=>setChosen(null)}>Cancel</button></div></form></div>}
 </>;
}
