import {useEffect,useState} from 'react';
import {download,request} from '../../api';
import type {State,User} from '../../types';
import {money} from '../../lib/format';
export function PosAdmin({state,user,refresh}:{state:State;user:User;refresh:()=>Promise<void>}){
 const [settings,setSettings]=useState<any>(null);const [menuId,setMenuId]=useState(0);const [item,setItem]=useState<any>(null);const [tableId,setTableId]=useState(0);const [table,setTable]=useState<any>(null);const [report,setReport]=useState<any>(null);const [audit,setAudit]=useState<any[]>([]);const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [branchName,setBranchName]=useState('');const [branches,setBranches]=useState<any[]>([]);const [branchId,setBranchId]=useState(0);const [staffId,setStaffId]=useState('');const [role,setRole]=useState('Waiter');
 useEffect(()=>{request('/pos/settings').then(setSettings).catch(e=>setError(e.message));if(user.owner)request('/owner/branches').then(setBranches).catch(e=>setError(e.message));},[]);
 const range=()=>{const from=new Date(date+'T00:00:00');const to=new Date(from);to.setDate(to.getDate()+1);return `from=${from.toISOString()}&to=${to.toISOString()}`;};
 async function run(work:()=>Promise<unknown>){setBusy(true);setError('');try{await work();await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const field=(label:string,key:string,value:any,set:(v:any)=>void,type='text')=><label className="field-label" key={key}>{label}<input type={type} value={value[key]??''} onChange={e=>set({...value,[key]:type==='number'?Number(e.target.value):e.target.value})}/></label>;
 return <section className="pos-panel"><h2>POS configuration & reports</h2>{error&&<p className="error" role="alert">{error}</p>}{settings&&<details><summary>Receipt, tax and service rules</summary>{[['Business name','businessName'],['Address','address'],['Tax ID','taxId'],['UPI address','upiId'],['Receipt footer','receiptFooter']].map(([l,k])=>field(l,k,settings,setSettings))}{field('Service charge percent','servicePercent',settings,setSettings,'number')}<label className="field-label">Tax rules<textarea value={settings.taxRulesJson} onChange={e=>setSettings({...settings,taxRulesJson:e.target.value})}/><small>Example: {`[{"Name":"CGST","Percent":2.5},{"Name":"SGST","Percent":2.5}]`}. Taxes apply after discount, including service charge. Choose rules appropriate for your business.</small></label><button className="primary" disabled={busy} onClick={()=>void run(()=>request('/pos/admin/settings','PUT',settings))}>Save billing settings</button></details>}
 <details><summary>Menu portions, modifiers and kitchen stations</summary><select aria-label="Menu item" value={menuId} onChange={e=>{const id=Number(e.target.value);setMenuId(id);setItem({...state.menu.find(m=>m.id===id)});}}><option value={0}>Choose item</option>{state.menu.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select>{item&&<>{field('Station','station',item,setItem)}{field('Photo HTTPS URL','photoUrl',item,setItem)}<label className="field-label">Portions<textarea value={item.portionsJson||'[]'} onChange={e=>setItem({...item,portionsJson:e.target.value})}/><small>{`[{"Name":"Half","Price":150},{"Name":"Full","Price":280}]`}</small></label><label className="field-label">Modifier groups<textarea value={item.modifiersJson||'[]'} onChange={e=>setItem({...item,modifiersJson:e.target.value})}/><small>{`[{"Name":"Cheese","Required":false,"Options":[{"Name":"Extra cheese","Price":30}]}]`}</small></label><button className="primary" disabled={busy} onClick={()=>void run(()=>request('/admin/menu/'+menuId,'PUT',item))}>Save menu configuration</button></>}</details>
 <details><summary>Floor positions and QR revocation</summary><select aria-label="Table" value={tableId} onChange={e=>{const id=Number(e.target.value);setTableId(id);setTable({...state.tables.find(t=>t.id===id)});}}><option value={0}>Choose table</option>{state.tables.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select>{table&&<>{field('Section','section',table,setTable)}{field('Horizontal position (0–1000)','x',table,setTable,'number')}{field('Vertical position (0–1000)','y',table,setTable,'number')}<button className="primary" disabled={busy} onClick={()=>void run(()=>request('/admin/tables/'+tableId,'PUT',table))}>Save floor position</button><button className="secondary" disabled={busy} onClick={()=>void run(()=>request(`/pos/admin/tables/${tableId}/rotate-qr`,'POST',{}))}>Replace QR and revoke old code</button></>}</details>
 <details><summary>End-of-day reconciliation & analytics</summary><label className="field-label">Service date (this device’s time zone)<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><div className="pos-actions"><button className="primary" disabled={busy} onClick={()=>void run(async()=>setReport(await request('/pos/admin/report?'+range())))}>Load report</button><button className="secondary" onClick={()=>void run(async()=>{const blob=await download('/pos/admin/report.csv?'+range());const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='tableflow-'+date+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);})}>Export CSV</button><button className="secondary" onClick={()=>window.print()}>Print / save PDF</button></div>{report&&<><div className="pos-columns">{['gross','discounts','taxes','serviceCharge','tips','closedSales','tenderCollected'].map(k=><div className="payment-row" key={k}><span>{k.replace(/[A-Z]/g,c=>' '+c.toLowerCase())}</span><strong>{money(report[k])}</strong></div>)}</div><h3>Tenders</h3>{report.byMethod.map((r:any)=><p key={r.methodId}>{state.paymentMethods.find(m=>m.id===r.methodId)?.name}: {money(r.total)}</p>)}<h3>Dish revenue</h3>{report.dishes.map((d:any)=><div className="payment-row" key={d.name}><span>{d.name} · {d.quantity} sold</span><strong>{money(d.revenue)}</strong></div>)}<h3>Ordering hours (UTC)</h3><div className="pos-actions">{report.hours.map((h:any)=><span className="hour-cell" style={{background:`rgba(20,110,75,${Math.min(1,.1+h.count/20)})`}} key={h.utcHour}>{h.utcHour}:00 · {h.count}</span>)}</div><h3>Preparation averages</h3>{report.preparation.map((p:any)=><p key={p.station}>{p.station}: {p.averageMinutes.toFixed(1)} minutes</p>)}<h3>Server sales</h3>{report.servers.map((s:any)=><p key={s.userId}>{state.users?.find(u=>u.id===s.userId)?.name||s.userId}: {money(s.sales)}</p>)}<p>Voided orders: {report.voids}</p></>}</details>
 <details><summary>Void and discount audit</summary><button className="secondary" disabled={busy} onClick={()=>void run(async()=>setAudit(await request('/pos/admin/audit')))}>Refresh audit</button>{audit.map(a=><div className="payment-row" key={a.id}><span>{new Date(a.createdAt).toLocaleString()} · {a.action}</span><span>{a.reason}</span></div>)}</details>
 {user.owner&&<details><summary>Branches & shared catalog</summary><label className="field-label">New branch name<input value={branchName} onChange={e=>setBranchName(e.target.value)}/></label><button className="secondary" disabled={busy||!branchName} onClick={()=>void run(async()=>{await request('/owner/branches','POST',{name:branchName,timeZone:'Asia/Kolkata'});setBranches(await request('/owner/branches'));setBranchName('');})}>Create branch</button><label className="field-label">Target branch<select value={branchId} onChange={e=>setBranchId(Number(e.target.value))}><option value={0}>Choose branch</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="field-label">Staff<select value={staffId} onChange={e=>setStaffId(e.target.value)}><option value="">Choose staff</option>{state.users?.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><select value={role} onChange={e=>setRole(e.target.value)}>{state.roles.map(r=><option key={r}>{r}</option>)}</select></label><button className="secondary" disabled={busy||!branchId||!staffId} onClick={()=>void run(()=>request(`/owner/branches/${branchId}/staff/${staffId}`,'PUT',{role}))}>Assign branch role</button><p>Select a menu item above to copy its catalog details. Existing branch base prices and stock are retained.</p><button className="secondary" disabled={busy||!branchId||!menuId} onClick={()=>void run(()=>request(`/owner/catalog/${menuId}/copy/${branchId}`,'POST',{}))}>Copy shared menu item</button></details>}
 </section>;
}
