import {Plus,Trash2} from 'lucide-react';
import {parse,type Portion,type Group} from './MenuPicker';
type Tax={Name:string;Percent:number};
export function TaxEditor({value,onChange}:{value:string;onChange:(value:string)=>void}){
 const rules=parse<Tax[]>(value,[]);const update=(next:Tax[])=>onChange(JSON.stringify(next));
 return <section><div className="editor-heading"><h3>Taxes</h3><button className="text-button" type="button" disabled={rules.length>=10} onClick={()=>update([...rules,{Name:'',Percent:0}])}><Plus size={15}/>Add tax</button></div>{rules.map((r,i)=><div className="form-row-editor" key={i}><label className="field-label">Tax name<input placeholder="e.g. CGST" value={r.Name} maxLength={60} onChange={e=>update(rules.map((t,j)=>i===j?{...t,Name:e.target.value}:t))}/></label><label className="field-label small-field">Rate (%)<input type="number" min="0" max="100" step="0.01" value={r.Percent} onChange={e=>update(rules.map((t,j)=>i===j?{...t,Percent:Number(e.target.value)}:t))}/></label><button className="icon-button" aria-label={`Remove tax ${r.Name||i+1}`} onClick={()=>update(rules.filter((_,j)=>j!==i))}><Trash2 size={17}/></button></div>)}{!rules.length&&<p className="section-description">No additional taxes. Add the rates that apply to your restaurant.</p>}<p className="section-description">Taxes apply after discounts and include the service charge.</p></section>;
}
export function PortionEditor({value,onChange}:{value:string;onChange:(value:string)=>void}){
 const portions=parse<Portion[]>(value,[]);const update=(next:Portion[])=>onChange(JSON.stringify(next));
 return <section><div className="editor-heading"><h3>Sizes & portions</h3><button className="text-button" disabled={portions.length>=20} onClick={()=>update([...portions,{Name:'',Price:0}])}><Plus size={15}/>Add size</button></div>{portions.map((p,i)=><div className="form-row-editor" key={i}><label className="field-label">Size name<input placeholder="e.g. Half, Full, Large" maxLength={60} value={p.Name} onChange={e=>update(portions.map((p,j)=>j===i?{...p,Name:e.target.value}:p))}/></label><label className="field-label small-field">Price (₹)<input type="number" min="0" step="0.01" value={p.Price} onChange={e=>update(portions.map((p,j)=>j===i?{...p,Price:Number(e.target.value)}:p))}/></label><button className="icon-button" aria-label={`Remove size ${p.Name||i+1}`} onClick={()=>update(portions.filter((_,j)=>j!==i))}><Trash2 size={17}/></button></div>)}{!portions.length&&<p className="section-description">One standard size, using the regular menu price.</p>}</section>;
}
export function ModifierEditor({value,onChange}:{value:string;onChange:(value:string)=>void}){
 const groups=parse<Group[]>(value,[]);const update=(next:Group[])=>onChange(JSON.stringify(next));const group=(i:number,next:Group)=>update(groups.map((g,j)=>j===i?next:g));
 return <section><div className="editor-heading"><h3>Extras & preferences</h3><button className="text-button" disabled={groups.length>=20} onClick={()=>update([...groups,{Name:'',Required:false,Options:[{Name:'',Price:0}]}])}><Plus size={15}/>Add group</button></div>{groups.map((g,i)=><div className="editor-group" key={i}><div className="form-row-editor"><label className="field-label">Group name<input placeholder="e.g. Toppings or spice level" maxLength={60} value={g.Name} onChange={e=>group(i,{...g,Name:e.target.value})}/></label><button className="icon-button" aria-label={`Remove group ${g.Name||i+1}`} onClick={()=>update(groups.filter((_,j)=>j!==i))}><Trash2 size={17}/></button></div><label className="checkbox"><input type="checkbox" checked={g.Required} onChange={e=>group(i,{...g,Required:e.target.checked})}/>Guest must choose an option</label>{g.Options.map((o,j)=><div className="form-row-editor" key={j}><label className="field-label">Option<input placeholder="e.g. Extra cheese" maxLength={60} value={o.Name} onChange={e=>group(i,{...g,Options:g.Options.map((o,k)=>k===j?{...o,Name:e.target.value}:o)})}/></label><label className="field-label small-field">Extra price (₹)<input type="number" min="0" step="0.01" value={o.Price} onChange={e=>group(i,{...g,Options:g.Options.map((o,k)=>k===j?{...o,Price:Number(e.target.value)}:o)})}/></label><button className="icon-button" disabled={g.Options.length<=1} aria-label={`Remove option ${o.Name||j+1}`} onClick={()=>group(i,{...g,Options:g.Options.filter((_,k)=>k!==j)})}><Trash2 size={15}/></button></div>)}<button className="secondary" disabled={g.Options.length>=30} onClick={()=>group(i,{...g,Options:[...g.Options,{Name:'',Price:0}]})}><Plus size={14}/>Add option</button></div>)}{!groups.length&&<p className="section-description">Add choices such as toppings, spice levels, or cooking preferences.</p>}</section>;
}
