import {useEffect,useState} from 'react';
import {ArrowRight,CheckCircle2,Receipt,Users} from 'lucide-react';
import {readDraft,writeDraft} from '../../api';
import type {State} from '../../types';
import {money} from '../../lib/format';
import {MenuPicker,OrderCart,linePrice,type Line} from '../pos/MenuPicker';

export function AdvancedOrderEntry({state,userId,busy,onSubmit}:{state:State;userId:string;busy:boolean;onSubmit:(body:any)=>Promise<boolean>}){
 const [saved]=useState(()=>readDraft(userId));const [table,setTable]=useState(saved?.table||state.tables[0]?.id||0);const [lines,setLines]=useState<Line[]>(saved?.lines||[]);const [notes,setNotes]=useState(saved?.notes||'');const [error,setError]=useState('');
 useEffect(()=>{try{writeDraft(userId,{table,lines,notes});setError('');}catch{setError('Draft storage unavailable. Keep this page open.');}},[userId,table,lines,notes]);
 const selected=state.tables.find(t=>t.id===table&&t.active);const count=lines.reduce((n,l)=>n+l.quantity,0);const subtotal=lines.reduce((n,l)=>n+l.quantity*linePrice(state.menu,l),0);
 return <div className="order-layout advanced-order"><div className="menu-workspace"><section className="table-selection"><div className="section-heading"><h2><span className="step">1</span>Pick a table</h2><span className="legend"><i/>Available<i className="occupied"/>In service</span></div><div className="table-grid">{state.tables.filter(t=>t.active).map(t=>{const occupied=state.sessions.some(s=>s.tableId===t.id&&!s.closedAt);return <button key={t.id} aria-pressed={table===t.id} className={'table-tile '+(table===t.id?'chosen ':'')+(occupied?'occupied':'')} onClick={()=>setTable(t.id)}><span className="table-number">{t.name}</span><span><Users size={13}/>{t.seats} seats</span><i/></button>;})}</div></section><section className="menu-section"><MenuPicker menu={state.menu} categories={state.categories} lines={lines} setLines={setLines} showCart={false}/></section></div>
 <aside className="order-summary"><div className="summary-title"><span className="summary-icon"><Receipt size={22}/></span><div><h2>Current order</h2><span>{selected?.name||'Choose a table'} · Dine-in</span></div><span className="count-pill">{count}</span></div><OrderCart menu={state.menu} lines={lines} setLines={setLines}/><label className="notes-label">A note for the kitchen<span>Optional</span><textarea value={notes} maxLength={500} onChange={e=>setNotes(e.target.value)} placeholder="Allergies, spice level, anything else…"/></label><div className="summary-total"><span>Subtotal <small>({count} items)</small></span><strong>{money(subtotal)}</strong></div><p className="billing-note">Final taxes, discounts, and payment are handled at reception.</p>{error&&<p role="alert" className="error">{error}</p>}<button className="primary submit-order" disabled={busy||!lines.length||!selected} onClick={async()=>{if(await onSubmit({tableId:table,items:lines,instructions:notes})){setLines([]);setNotes('');}}}>{busy?'Sending your order…':'Send to kitchen'}<ArrowRight size={18}/></button><div className="auto-note"><CheckCircle2 size={14}/>Your draft is saved on this device</div></aside></div>;
}
