import { ArrowRight,Check,ChefHat,Leaf,Minus,Plus,Receipt,Search,ShoppingBag,SlidersHorizontal,Users,X } from 'lucide-react';
import { useEffect,useState } from 'react';
import { orderSignature } from '../../../../shared/network.mjs';
import { draftBody,readDraft,writeDraft } from '../../api';
import { Empty } from '../../components/Empty';
import { money } from '../../lib/format';
import type { State } from '../../types';

export function OrderEntry({state,busy,onSubmit,userId}:{state:State;busy:boolean;userId:string;onSubmit:(r:any)=>Promise<boolean>}){
 const [saved]=useState(()=>readDraft(userId));const [draftError,setDraftError]=useState('');const [table,setTable]=useState(saved?.table||1);const [category,setCategory]=useState(0);const [query,setQuery]=useState('');const [cart,setCart]=useState<Record<number,number>>(saved?.cart||{});const [notes,setNotes]=useState(saved?.notes||'');
 useEffect(()=>{try{writeDraft(userId,{table,cart,notes});setDraftError('');}catch{setDraftError('Device storage is unavailable. Keep this screen open so you do not lose the draft.');}},[userId,table,cart,notes]);
 useEffect(()=>{const confirmed=(e:Event)=>{if((e as CustomEvent).detail?.userId===userId&&(e as CustomEvent).detail?.signature===orderSignature(draftBody({table,cart,notes}))){setCart({});setNotes('');}};window.addEventListener('order-confirmed',confirmed);return()=>window.removeEventListener('order-confirmed',confirmed);},[table,cart,notes]);
 const items=state.menu.filter(m=>m.active&&(category===0||m.categoryId===category)&&m.name.toLowerCase().includes(query.toLowerCase()));const chosen=state.menu.filter(m=>cart[m.id]);const subtotal=chosen.reduce((n,m)=>n+cart[m.id]*m.price,0);const count=Object.values(cart).reduce((n,x)=>n+x,0);
 const add=(id:number,delta:number)=>setCart(c=>({...c,[id]:Math.max(0,Math.min(99,(c[id]||0)+delta))}));
 return <><div className="draft-status" role="status">{draftError||'Draft saved on this device · Send when you have a connection.'}</div><div className="order-layout"><div className="menu-workspace"><section className="table-selection"><div className="section-heading"><h2><span className="step">1</span>Select a table</h2><span className="legend"><i/>Available <i className="occupied"/>In service</span></div><div className="table-grid">{state.tables.filter(t=>t.active).map(t=>{const occupied=state.sessions.some(s=>s.tableId===t.id&&!s.closedAt);return <button key={t.id} onClick={()=>setTable(t.id)} className={`table-tile ${table===t.id?'chosen':''} ${occupied?'occupied':''}`} aria-pressed={table===t.id}><span className="table-number">{t.name}</span><span><Users size={13}/>{t.seats} seats</span><i/>{table===t.id&&<Check className="table-check" size={13}/>}</button>;})}</div></section>
 <section className="menu-section"><div className="section-heading"><h2><span className="step">2</span>Build the order</h2><span className="muted">{state.menu.filter(m=>m.active).length} items on the menu</span></div><div className="menu-toolbar"><label className="search"><Search size={18}/><input placeholder="Search food or beverages…" value={query} onChange={e=>setQuery(e.target.value)}/><span>⌕</span></label><div className="menu-count"><SlidersHorizontal size={18}/></div></div><div className="category-tabs">{[{id:0,name:'All items'},...state.categories].map(c=><button key={c.id} className={category===c.id?'active':''} onClick={()=>setCategory(c.id)}>{c.name}</button>)}</div><div className="menu-grid">{items.map(m=><article key={m.id} className="menu-card"><div className="menu-card-top"><span className={`diet ${m.vegetarian?'veg':'nonveg'}`} title={m.vegetarian?'Vegetarian':'Non vegetarian'}><i/></span><span>{state.categories.find(c=>c.id===m.categoryId)?.name}</span>{m.vegetarian&&<Leaf size={15}/>}</div><h3>{m.name}</h3><p>{m.description}</p><div className="menu-card-bottom"><strong>{money(m.price)}</strong>{cart[m.id]?<div className="quantity"><button aria-label={`Remove one ${m.name}`} onClick={()=>add(m.id,-1)}><Minus size={14}/></button><span>{cart[m.id]}</span><button aria-label={`Add one ${m.name}`} onClick={()=>add(m.id,1)}><Plus size={14}/></button></div>:<button className="add-button" onClick={()=>add(m.id,1)}>Add <Plus size={15}/></button>}</div></article>)}</div>{!items.length&&<Empty text="No matching items. Try another search."/>}</section></div>
 <aside className="order-summary"><div className="summary-title"><div className="summary-icon"><Receipt size={21}/></div><div><h2>Current order</h2><span>{state.tables.find(t=>t.id===table)?.name} <i/> Dine-in</span></div><span className="count-pill">{count}</span></div><div className="summary-items">{chosen.length?chosen.map(m=><div className="cart-item" key={m.id}><div><strong>{m.name}</strong><small>{money(m.price)} each</small><div className="quantity"><button aria-label={`Decrease ${m.name}`} onClick={()=>add(m.id,-1)}><Minus size={13}/></button><span>{cart[m.id]}</span><button aria-label={`Increase ${m.name}`} onClick={()=>add(m.id,1)}><Plus size={13}/></button></div></div><div><strong>{money(m.price*cart[m.id])}</strong><button className="remove-item" aria-label={`Remove ${m.name}`} onClick={()=>setCart(c=>({...c,[m.id]:0}))}><X size={14}/></button></div></div>):<div className="cart-empty"><ShoppingBag size={36}/><h3>A good meal starts here.</h3><p>Add items from the menu<br/>to build this table’s order.</p></div>}</div><label className="notes-label">Special instructions <span>Optional</span><textarea maxLength={500} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Allergies, spice level, or any special requests…"/></label><div className="summary-total"><span>Subtotal <small>({count} items)</small></span><strong>{money(subtotal)}</strong></div><p className="billing-note">Final bill is collected at reception.</p><button className="primary submit-order" disabled={!count||busy} onClick={async()=>{if(await onSubmit({tableId:table,items:chosen.map(m=>({menuItemId:m.id,quantity:cart[m.id]})),instructions:notes})){/* Cleared by the matching acknowledgement event. */}}}>{busy?'Waiting for confirmation…':'Send to kitchen'}<ArrowRight size={18}/></button><div className="auto-note"><ChefHat size={15}/>Sent only after server confirmation</div></aside></div></>;
}
