import {PosBilling} from './features/cashier/PosBilling';
import {PosAdmin} from './features/pos/PosAdmin';
import {FloorMap} from './features/pos/FloorMap';
import {AccountTools} from './features/pos/AccountTools';
import { ArrowRight,Bell,Check,CheckCircle2,ChefHat,Clock,LayoutGrid,LogOut,Receipt,Settings,ShoppingBag,UtensilsCrossed,Wallet,X } from 'lucide-react';
import { useEffect,useMemo,useRef,useState } from 'react';
import { coalescedRefresh } from '../../shared/network.mjs';
import { action,cachedState,demo,demoState,getPending,getState,logout,restoreSession,subscribe } from './api';
import { Empty } from './components/Empty';
import { Stat } from './components/Stat';
import { Admin } from './features/admin/Admin';
import { Login } from './features/auth/Login';
import { Billing } from './features/cashier/Billing';
import { KitchenScreen } from './features/kitchen/KitchenScreen';
import { WaiterScreen } from './features/waiter/WaiterScreen';
import { money } from './lib/format';
import type { Role,State,User } from './types';

export const restoredUser=demo?demoState().users[0]:restoreSession();

export const roles:{role:Role;name:string;icon:typeof LayoutGrid}[]=[{role:'Waiter',name:'Waiter / Supplier',icon:LayoutGrid},{role:'Kitchen',name:'Kitchen',icon:ChefHat},{role:'Cashier',name:'Reception / Cashier',icon:Receipt},{role:'Admin',name:'Admin',icon:Settings}];

export function App(){
 const [user,setUser]=useState<User|null>(restoredUser);const [role,setRole]=useState<Role>(restoredUser?.role||'Waiter');const [state,setState]=useState<State|null>(demo?demoState():cachedState(restoredUser));const [tab,setTab]=useState('new');const [toast,setToast]=useState('');const [error,setError]=useState('');const [connection,setConnection]=useState('Connecting…');const [busy,setBusy]=useState(false);const [showNotifications,setShowNotifications]=useState(false);
 const [syncError,setSyncError]=useState('');const [lastSync,setLastSync]=useState(0);const [syncing,setSyncing]=useState(false);const [pending,setPending]=useState<any>(user?getPending(user.id):null);const submitting=useRef(false);const currentUserId=useRef(user?.id);currentUserId.current=user?.id;
 const refresh=useMemo(()=>coalescedRefresh(async()=>{const id=user?.id;setSyncing(true);try{const result=await getState();if(id===currentUserId.current){setState(result);setSyncError('');setLastSync(Date.now());if(!demo)setConnection('Connected');}}catch(e){if(id===currentUserId.current)setSyncError((e as Error).message);}finally{if(id===currentUserId.current)setSyncing(false);}}),[user?.id]);
 useEffect(()=>{const changed=()=>setPending(user?getPending(user.id):null);changed();window.addEventListener('pending-change',changed);window.addEventListener('storage',changed);return()=>{window.removeEventListener('pending-change',changed);window.removeEventListener('storage',changed);};},[user?.id]);
 useEffect(()=>{if(!user)return;void refresh();return subscribe(refresh,setToast,setConnection);},[user?.id]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(t);}},[toast]);
 useEffect(()=>{const expired=()=>{logout();setUser(null);setState(null);};window.addEventListener('session-expired',expired);return()=>window.removeEventListener('session-expired',expired);},[]);
 useEffect(()=>{const t=setInterval(()=>setState(s=>s?{...s}:s),60000);return()=>clearInterval(t);},[]);
 async function run(path:string,body:unknown,message:string,method='POST'){if(submitting.current||!user)return false;submitting.current=true;setBusy(true);setError('');try{await action(path,body,user,method);void refresh();setToast(message);return true;}catch(e){setError((e as Error).message);return false;}finally{submitting.current=false;setBusy(false);}}
 function switchRole(r:Role){setRole(r);setTab('new');if(demo)setUser(state!.users.find(u=>u.role===r)!);}
 if(!user)return <Login onLogin={u=>{setUser(u);setRole(u.role);}}/>;
 if(!state)return <div className="loading"><UtensilsCrossed/><h2>Opening your workspace…</h2>{(error||syncError)&&<><p>{error||syncError}</p><button onClick={()=>void refresh()}>Retry connection</button><button onClick={()=>{logout();setUser(null);}}>Back to sign in</button></>}</div>;
 const own=state.orders.filter(o=>role!=='Waiter'||o.waiterId===user.id);const active=own.filter(o=>!['Paid','Voided'].includes(o.status));const ready=active.filter(o=>o.status==='Ready');const notifications=state.notifications.filter(n=>n.userId===user.id&&!n.read);
 return <div className="app"><aside className="sidebar"><a className="brand" href="#"><span className="brand-icon"><UtensilsCrossed size={23}/></span><span>tableflow<span className="brand-dot">.</span></span></a><div className="restaurant"><div className="restaurant-avatar">T</div><div><strong>The Table House</strong><small>Restaurant workspace</small></div></div><div className="nav-label">WORKSPACES</div><nav>{roles.filter(r=>demo||user.role==='Admin'||r.role===user.role).map(r=><button key={r.role} className={role===r.role?'nav-item selected':'nav-item'} onClick={()=>switchRole(r.role)}><r.icon size={20}/><span>{r.name}</span>{r.role==='Kitchen'&&<em>{state.orders.filter(o=>['New','Preparing'].includes(o.status)).length}</em>}</button>)}</nav><div className="sidebar-bottom"><div className="service-note"><span className="service-dot"/><strong>Service in progress</strong><p>Good food. Smooth service.</p></div><div className="profile"><div className="avatar">{user.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><strong>{user.name}</strong><small>{user.role==='Waiter'?'Floor staff':user.role}</small></div>{!demo&&<button className="icon-button" aria-label="Sign out" onClick={()=>{logout();setUser(null);}}><LogOut size={18}/></button>}</div></div></aside>
 <div className="workspace"><header className="topbar"><div><span className="breadcrumb">Workspace</span><span className="slash">/</span><strong>{roles.find(r=>r.role===role)?.name}</strong></div><div className="top-actions"><span className={`connection ${demo?'demo':''}`}><span/>{connection}</span><span className="date">{new Date().toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}</span><button className="notification-button" aria-label="Notifications" onClick={()=>setShowNotifications(!showNotifications)}><Bell size={21}/>{notifications.length>0&&<b>{notifications.length}</b>}</button></div></header>
 {demo&&<div className="demo-banner"><span>Interactive demo · Changes are saved in this browser. Online PostgreSQL is not connected.</span><span>Try every workspace <ArrowRight size={14}/></span></div>}
 <main><div className="page-heading"><div><div className="eyebrow">{role==='Waiter'?'FLOOR OPERATIONS':role==='Kitchen'?'KITCHEN OPERATIONS':role==='Cashier'?'RECEPTION & PAYMENTS':'RESTAURANT CONTROL'}</div><h1>{role==='Waiter'?'Let’s make service seamless.':role==='Kitchen'?'On the pass.':role==='Cashier'?'A great meal, all settled.':'Everything in good order.'}</h1><p>{role==='Waiter'?'Take orders, keep an eye on the kitchen, and serve with confidence.':role==='Kitchen'?'Every ticket, from the first sizzle to ready for service.':role==='Cashier'?'Review served orders and close each table with a single bill.':'Manage your menu, team, tables, and daily performance.'}</p></div><div className="shift"><Clock size={17}/><div><strong>Today’s service</strong><small>{new Date().toLocaleDateString('en-IN',{weekday:'long'})}</small></div></div></div>
 {error&&<div role="alert" className="error">{error}<button onClick={()=>setError('')} aria-label="Dismiss error"><X size={16}/></button></div>}
 <div className={syncError?'sync-strip stale':'sync-strip'} role="status"><span>{syncing?'Checking for updates…':lastSync?'Last updated '+new Date(lastSync).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'}):'Showing the saved workspace'}{syncError&&' · '+syncError}</span><button className="secondary" disabled={syncing} onClick={()=>void refresh()}>Refresh status</button></div>
 {pending&&<div className="pending-order" role="status"><div><strong>Order confirmation pending · Table {pending.body.tableId}</strong><p>Your order is safely stored on this device. Check confirmation before placing it again.</p></div><button disabled={busy} className="primary" onClick={()=>run('/orders',pending.body,'Order confirmed with the kitchen')}>Check order confirmation</button></div>}
 <div className="stats"><Stat icon={LayoutGrid} label="Tables in service" value={state.sessions.filter(s=>!s.closedAt).length} sub={`${state.tables.filter(t=>t.active).length} tables on the floor`}/><Stat icon={ShoppingBag} label="Active orders" value={active.filter(o=>o.status!=='Served').length} sub="Moving through the kitchen"/><Stat icon={CheckCircle2} label="Ready to serve" value={ready.length} sub="Fresh from the kitchen" accent/><Stat icon={role==='Cashier'||role==='Admin'?Wallet:Check} label={role==='Cashier'||role==='Admin'?'Sales today':'Served orders'} value={role==='Cashier'||role==='Admin'?money(state.bills.filter(b=>new Date(b.paidAt).toDateString()===new Date().toDateString()).reduce((s,b)=>s+b.total,0)):own.filter(o=>['Served','Paid'].includes(o.status)&&new Date(o.createdAt).toDateString()===new Date().toDateString()).length} sub="Today’s completed service"/></div>
 {role==='Waiter'&&<WaiterScreen state={state} user={user} tab={tab} setTab={setTab} active={active} ready={ready} busy={busy} run={run}/>}
 {role==='Kitchen'&&<KitchenScreen state={state} busy={busy} run={run}/>}
 {role==='Cashier'&&(demo?<Billing state={state} busy={busy} run={run}/>:<PosBilling state={state} user={user}/>)}
 {role==='Admin'&&<Admin state={state} busy={busy} run={run}/>}
 {!demo&&<><AccountTools user={user}/><FloorMap state={state} user={user} refresh={refresh}/>{role==='Admin'&&<PosAdmin state={state} user={user} refresh={refresh}/>}<section className="pos-panel"><h2>Guest requests</h2>{((state as any).guestRequests||[]).map((r:any)=><div className="payment-row" key={r.id}><span>Table {r.tableId} · {r.kind}</span><button className="secondary" disabled={busy} onClick={()=>run('/pos/guest-requests/'+r.id+'/resolve',{},'Request resolved')}>Resolve</button></div>)}</section>{user.role==='Admin'&&<details className="pos-panel"><summary>Void an order</summary>{state.orders.filter(o=>!['Paid','Voided'].includes(o.status)).map(o=><div className="payment-row" key={o.id}><span>Table {o.tableId} · {o.id.slice(0,8)}</span><select aria-label="Void reason" defaultValue="" onChange={e=>{if(e.target.value)void run('/pos/admin/orders/'+o.id+'/void',{reason:e.target.value},'Void recorded');}}><option value="">Choose reason to void</option>{['Kitchen Error','Customer Changed Mind','Quality Issue','Spillage'].map(r=><option key={r}>{r}</option>)}</select></div>)}</details>}</>}<footer><UtensilsCrossed size={14}/> Tableflow <span>Made for a smoother service.</span></footer></main></div>
 {showNotifications&&<div className="notification-panel"><div className="panel-heading"><h2>Notifications</h2><button className="icon-button" aria-label="Close notifications" onClick={()=>setShowNotifications(false)}><X/></button></div>{notifications.length?notifications.map(n=><div className="notification" key={n.id}><CheckCircle2 size={20}/><div><strong>{n.message}</strong><small>Collect the order from the kitchen.</small></div><button className="icon-button" aria-label="Mark read" onClick={()=>run(`/notifications/${n.id}/read`,{},'Notification cleared')}><Check size={18}/></button></div>):<Empty text="You’re all caught up."/>}</div>}
 {toast&&<div className="toast" role="status"><CheckCircle2 size={20}/>{toast}<button aria-label="Dismiss notification" onClick={()=>setToast('')}><X size={17}/></button></div>}</div>;
}
