export function initialState(){
 const menu=[['Paneer tikka','Smoky tandoor · mint chutney',1,280,true],['Crispy corn','Golden corn · pepper & lime',1,180,true],['Butter chicken','Tandoori chicken · creamy tomato',2,360,false],['Dal makhani','Slow-cooked black lentils',2,260,true],['Veg dum biryani','Fragrant basmati · garden vegetables',2,290,true],['Garlic naan','Tandoor baked · garlic butter',3,70,true],['Jeera rice','Basmati rice · roasted cumin',3,150,true],['Fresh lime soda','Fresh lime · chilled soda',4,90,true],['Mango lassi','Alphonso mango · creamy yogurt',4,140,true],['Gulab jamun','Two warm dumplings · rose syrup',5,120,true]].map((x,i)=>({id:i+1,name:x[0],description:x[1],categoryId:x[2],price:x[3],vegetarian:x[4],active:true}));
 const users=['Waiter','Kitchen','Cashier','Admin'].map((role,i)=>({id:`demo-${role}`,name:['Aarav Sharma','Kitchen team','Priya Mehta','Restaurant admin'][i],email:`${role.toLowerCase()}@demo.local`,role,active:true}));
 const s={categories:['Starters','Main course','Breads & sides','Beverages','Desserts'].map((name,i)=>({id:i+1,name})),menu,tables:Array.from({length:12},(_,i)=>({id:i+1,name:`Table ${String(i+1).padStart(2,'0')}`,seats:i>7?6:4,active:true})),paymentMethods:['Cash','Card','UPI'].map((name,i)=>({id:i+1,name,active:true})),sessions:[],orders:[],notifications:[],bills:[],users,roles:['Waiter','Kitchen','Cashier','Admin']};
 for(const [tableId,status,items,minutes] of [[3,'Preparing',[[3,2],[6,4]],12],[5,'Ready',[[1,1],[9,2]],8],[8,'Served',[[4,1],[6,3],[8,2]],24]]){const sessionId=crypto.randomUUID();s.sessions.push({id:sessionId,tableId,closedAt:null});s.orders.push({id:crypto.randomUUID(),sessionId,tableId,waiterId:'demo-Waiter',status,instructions:tableId===3?'Less spicy, please.':tableId===5?'Lassi without ice.':'',createdAt:new Date(Date.now()-minutes*60000).toISOString(),items:items.map(([id,quantity])=>({menuItemId:id,name:menu[id-1].name,quantity,unitPrice:menu[id-1].price}))});}
 return s;
}
export function mutate(s,path,body,user){
 if(path==='/orders'){
 if(!['Waiter','Admin'].includes(user.role))throw Error('Only waiters can place orders.');
 if(!s.tables.some(t=>t.id===body.tableId&&t.active)||!body.items.length)throw Error('Choose a table and at least one item.');
 const items=body.items.map(i=>{const m=s.menu.find(m=>m.id===i.menuItemId&&m.active);if(!m||i.quantity<1||i.quantity>99)throw Error('Invalid item or quantity.');return {menuItemId:m.id,name:m.name,quantity:i.quantity,unitPrice:m.price};});
 let session=s.sessions.find(x=>x.tableId===body.tableId&&!x.closedAt);if(!session){session={id:crypto.randomUUID(),tableId:body.tableId,closedAt:null};s.sessions.push(session);}s.orders.unshift({id:crypto.randomUUID(),sessionId:session.id,tableId:body.tableId,waiterId:user.id,status:'New',instructions:body.instructions||'',createdAt:new Date().toISOString(),items});
 }else if(path.includes('/status')){
 const order=s.orders.find(o=>o.id===path.split('/')[2]);if(!order)throw Error('Order not found.');const next={New:'Preparing',Preparing:'Ready',Ready:'Served'}[order.status];if(body.status!==next)throw Error('Invalid status transition.');if(user.role!=='Admin'&&(body.status==='Served'?user.role!=='Waiter'||user.id!==order.waiterId:user.role!=='Kitchen'))throw Error('This action is not permitted.');order.status=next;if(next==='Ready')s.notifications.unshift({id:crypto.randomUUID(),userId:order.waiterId,message:`Food ready · Table ${order.tableId}`,read:false});
 }else if(path.includes('/pay')){
 if(!['Admin','Cashier'].includes(user.role))throw Error('Cashier access required.');const id=path.split('/')[2];if(s.bills.some(b=>b.sessionId===id))return s;const orders=s.orders.filter(o=>o.sessionId===id);if(!orders.length||orders.some(o=>o.status!=='Served'))throw Error('All orders must be served before payment.');const total=orders.reduce((n,o)=>n+o.items.reduce((n,i)=>n+i.quantity*i.unitPrice,0),0);if(Math.round(total*100)/100!==body.expectedTotal)throw Error('Bill total changed.');if(!s.paymentMethods.some(m=>m.id===body.paymentMethodId&&m.active))throw Error('Choose an active payment method.');const session=s.sessions.find(x=>x.id===id);session.closedAt=new Date().toISOString();orders.forEach(o=>o.status='Paid');s.bills.unshift({id:crypto.randomUUID(),sessionId:id,tableId:session.tableId,total,paymentMethodId:body.paymentMethodId,reference:body.reference||'',paidAt:session.closedAt});
 }else if(path.startsWith('/admin/')){
 if(user.role!=='Admin')throw Error('Administrator access required.');const [, ,collection,id]=path.split('/');const list=s[collection];if(!list)throw Error('Unknown collection');let row=list.find(x=>String(x.id)===id);const clean={...body};delete clean.password;if(row)Object.assign(row,clean);else list.push({...clean,id:collection==='users'?crypto.randomUUID():Math.max(0,...list.map(x=>x.id))+1});
 }else if(path.startsWith('/notifications/')){const n=s.notifications.find(x=>x.id===path.split('/')[2]&&x.userId===user.id);if(n)n.read=true;}
 else throw Error('Unknown action');return s;
}

