import {kitchenAge} from '../../../shared/kitchen.mjs';
import {PrintButton} from '../features/pos/PrintButton';
import {demo} from '../api';
import { Check,Clock } from 'lucide-react';
import type { Runner } from '../lib/actions';
import { elapsed,money,short,total } from '../lib/format';
import type { Order,Role,State } from '../types';
import { Empty } from './Empty';

export function Orders({orders,state,role,busy,run}:{orders:Order[];state:State;role:Role;busy:boolean;run:Runner}){return <div className="orders-grid">{orders.length?orders.map(o=><article className={`ticket ${role==='Kitchen'&&o.status!=='Ready'?'sla-'+kitchenAge(o.createdAt).level:''}`} key={o.id}><div className="ticket-header"><div><span className="eyebrow">ORDER #{short(o.id)}</span><h2>{state.tables.find(t=>t.id===o.tableId)?.name}</h2></div><span className={`badge ${o.status}`}>{o.status}</span></div><div className="ticket-time"><Clock size={14}/>{elapsed(o.createdAt)} ago <span>{new Date(o.createdAt).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}</span></div><div className="ticket-items">{o.items.map((i,n)=>{let mods:{group:string;option:string}[]=[];try{mods=JSON.parse(i.modifiersJson||'[]');}catch{}return <div key={n} style={{marginBottom:'6px'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'baseline'}}><div><b>{i.quantity}×</b> <span style={{fontWeight:600}}>{i.name}</span>{i.portion?<span style={{marginLeft:'6px',fontSize:'11px',padding:'2px 6px',borderRadius:'4px',background:'#e8f0fe',color:'#1967d2',fontWeight:500}}>{i.portion}</span>:null}{i.station&&i.station!=='Kitchen'?<span style={{marginLeft:'6px',fontSize:'11px',padding:'2px 6px',borderRadius:'4px',background:'#fef3c7',color:'#92400e',fontWeight:500}}>{i.station}</span>:null}</div>{role!=='Kitchen'&&<strong>{money(i.quantity*i.unitPrice)}</strong>}</div>{mods.length>0&&<div style={{display:'flex',flexWrap:'wrap',gap:'4px',marginLeft:'20px',marginTop:'2px'}}>{mods.map((m,idx)=><span key={idx} style={{fontSize:'11px',background:'#f1f5f9',color:'#475569',padding:'1px 5px',borderRadius:'3px'}}>+ {m.option}</span>)}</div>}</div>;})}</div>{o.instructions&&<p className="instructions">{o.instructions}</p>}<div className="ticket-bottom">{role==='Waiter'&&<strong>{money(total(o))}</strong>}{role==='Kitchen'&&o.status!=='Ready'?<button className="primary" disabled={busy} onClick={()=>run(`/orders/${o.id}/status`,{status:o.status==='New'?'Preparing':'Ready'},o.status==='New'?'Preparation started':'Waiter notified: food is ready')}>{o.status==='New'?'Start preparing':'Mark ready'}<Check size={16}/></button>:role==='Waiter'&&o.status==='Ready'?<button className="primary" disabled={busy} onClick={()=>run(`/orders/${o.id}/status`,{status:'Served'},'Order served and sent to reception')}>Mark served <Check size={16}/></button>:<span className="muted">{o.status==='Ready'?'Waiting for collection':o.status==='Served'?'Sent to reception':'Kitchen is on it'}</span>}</div>{!demo&&<PrintButton kind="kot" id={o.id}/>}</article>):<Empty text="No orders here right now."/>}</div>;}
