import {kitchenAge} from '../../../shared/kitchen.mjs';
import {PrintButton} from '../features/pos/PrintButton';
import {demo} from '../api';
import { Check,Clock } from 'lucide-react';
import type { Runner } from '../lib/actions';
import { elapsed,money,short,total } from '../lib/format';
import type { Order,Role,State } from '../types';
import { Empty } from './Empty';

export function Orders({orders,state,role,busy,run}:{orders:Order[];state:State;role:Role;busy:boolean;run:Runner}){return <div className="orders-grid">{orders.length?orders.map(o=><article className={`ticket ${role==='Kitchen'&&o.status!=='Ready'?'sla-'+kitchenAge(o.createdAt).level:''}`} key={o.id}><div className="ticket-header"><div><span className="eyebrow">ORDER #{short(o.id)}</span><h2>{state.tables.find(t=>t.id===o.tableId)?.name}</h2></div><span className={`badge ${o.status}`}>{o.status}</span></div><div className="ticket-time"><Clock size={14}/>{elapsed(o.createdAt)} ago <span>{new Date(o.createdAt).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}</span></div><div className="ticket-items">{o.items.map((i,n)=><div key={n}><b>{i.quantity}×</b><span>{i.name}</span>{role!=='Kitchen'&&<strong>{money(i.quantity*i.unitPrice)}</strong>}</div>)}</div>{o.instructions&&<p className="instructions">{o.instructions}</p>}<div className="ticket-bottom">{role==='Waiter'&&<strong>{money(total(o))}</strong>}{role==='Kitchen'&&o.status!=='Ready'?<button className="primary" disabled={busy} onClick={()=>run(`/orders/${o.id}/status`,{status:o.status==='New'?'Preparing':'Ready'},o.status==='New'?'Preparation started':'Waiter notified: food is ready')}>{o.status==='New'?'Start preparing':'Mark ready'}<Check size={16}/></button>:role==='Waiter'&&o.status==='Ready'?<button className="primary" disabled={busy} onClick={()=>run(`/orders/${o.id}/status`,{status:'Served'},'Order served and sent to reception')}>Mark served <Check size={16}/></button>:<span className="muted">{o.status==='Ready'?'Waiting for collection':o.status==='Served'?'Sent to reception':'Kitchen is on it'}</span>}</div>{!demo&&<PrintButton kind="kot" id={o.id}/>}</article>):<Empty text="No orders here right now."/>}</div>;}
